(function(){/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var Qa="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
(function(){function g(){var a=this;this.s={};this.g=document.documentElement;var b=new na;b.rules=[];this.h=t.set(this.g,new t(b));this.i=!1;this.b=this.a=null;Ra(function(){a.c()})}function C(){this.customStyles=[];this.enqueued=!1}function Sa(){}function X(a){this.cache={};this.f=void 0===a?100:a}function k(){}function t(a,b,c,d,e){this.D=a||null;this.b=b||null;this.fa=c||[];this.K=null;this.R=e||"";this.a=this.B=this.G=null}function r(){}function na(){this.end=this.start=0;this.rules=this.parent=
this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}function Rb(a){function b(b,c){Object.defineProperty(b,"innerHTML",{enumerable:c.enumerable,configurable:!0,get:c.get,set:function(b){var d=this,e=void 0;m(this)&&(e=[],I(this,function(a){a!==d&&e.push(a)}));c.set.call(this,b);if(e)for(var f=0;f<e.length;f++){var l=e[f];1===l.__CE_state&&a.disconnectedCallback(l)}this.ownerDocument.__CE_hasRegistry?a.f(this):a.l(this);
return b}})}function c(b,c){p(b,"insertAdjacentElement",function(b,d){var e=m(d);b=c.call(this,b,d);e&&a.a(d);m(b)&&a.b(d);return b})}Ta&&p(Element.prototype,"attachShadow",function(a){return this.__CE_shadowRoot=a=Ta.call(this,a)});if(oa&&oa.get)b(Element.prototype,oa);else if(pa&&pa.get)b(HTMLElement.prototype,pa);else{var d=qa.call(document,"div");a.w(function(a){b(a,{enumerable:!0,configurable:!0,get:function(){return Ua.call(this,!0).innerHTML},set:function(a){var b="template"===this.localName?
this.content:this;for(d.innerHTML=a;0<b.childNodes.length;)ra.call(b,b.childNodes[0]);for(;0<d.childNodes.length;)Y.call(b,d.childNodes[0])}})})}p(Element.prototype,"setAttribute",function(b,c){if(1!==this.__CE_state)return Va.call(this,b,c);var d=sa.call(this,b);Va.call(this,b,c);c=sa.call(this,b);a.attributeChangedCallback(this,b,d,c,null)});p(Element.prototype,"setAttributeNS",function(b,c,d){if(1!==this.__CE_state)return Wa.call(this,b,c,d);var e=Z.call(this,b,c);Wa.call(this,b,c,d);d=Z.call(this,
b,c);a.attributeChangedCallback(this,c,e,d,b)});p(Element.prototype,"removeAttribute",function(b){if(1!==this.__CE_state)return Xa.call(this,b);var c=sa.call(this,b);Xa.call(this,b);null!==c&&a.attributeChangedCallback(this,b,c,null,null)});p(Element.prototype,"removeAttributeNS",function(b,c){if(1!==this.__CE_state)return Ya.call(this,b,c);var d=Z.call(this,b,c);Ya.call(this,b,c);var e=Z.call(this,b,c);d!==e&&a.attributeChangedCallback(this,c,d,e,b)});Za?c(HTMLElement.prototype,Za):$a?c(Element.prototype,
$a):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");ta(a,Element.prototype,{V:Tb,append:Ub});Vb(a,{da:Wb,Da:Xb,replaceWith:Yb,remove:Zb})}function Vb(a,b){var c=Element.prototype;function d(b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];e=[];for(var f=[],g=0;g<d.length;g++){var n=d[g];n instanceof Element&&m(n)&&f.push(n);if(n instanceof DocumentFragment)for(n=n.firstChild;n;n=n.nextSibling)e.push(n);else e.push(n)}b.apply(this,
d);for(d=0;d<f.length;d++)a.a(f[d]);if(m(this))for(d=0;d<e.length;d++)f=e[d],f instanceof Element&&a.b(f)}}void 0!==b.da&&(c.before=d(b.da));void 0!==b.da&&(c.after=d(b.Da));void 0!==b.replaceWith&&p(c,"replaceWith",function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];e=[];for(var h=[],q=0;q<d.length;q++){var g=d[q];g instanceof Element&&m(g)&&h.push(g);if(g instanceof DocumentFragment)for(g=g.firstChild;g;g=g.nextSibling)e.push(g);else e.push(g)}q=m(this);b.replaceWith.apply(this,
d);for(d=0;d<h.length;d++)a.a(h[d]);if(q)for(a.a(this),d=0;d<e.length;d++)h=e[d],h instanceof Element&&a.b(h)});void 0!==b.remove&&p(c,"remove",function(){var c=m(this);b.remove.call(this);c&&a.a(this)})}function $b(a){function b(b,d){Object.defineProperty(b,"textContent",{enumerable:d.enumerable,configurable:!0,get:d.get,set:function(b){if(this.nodeType===Node.TEXT_NODE)d.set.call(this,b);else{var c=void 0;if(this.firstChild){var e=this.childNodes,h=e.length;if(0<h&&m(this)){c=Array(h);for(var q=
0;q<h;q++)c[q]=e[q]}}d.set.call(this,b);if(c)for(b=0;b<c.length;b++)a.a(c[b])}}})}p(Node.prototype,"insertBefore",function(b,d){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=ab.call(this,b,d);if(m(this))for(d=0;d<c.length;d++)a.b(c[d]);return b}c=m(b);d=ab.call(this,b,d);c&&a.a(b);m(this)&&a.b(b);return d});p(Node.prototype,"appendChild",function(b){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=Y.call(this,b);if(m(this))for(var e=
0;e<c.length;e++)a.b(c[e]);return b}c=m(b);e=Y.call(this,b);c&&a.a(b);m(this)&&a.b(b);return e});p(Node.prototype,"cloneNode",function(b){b=Ua.call(this,b);this.ownerDocument.__CE_hasRegistry?a.f(b):a.l(b);return b});p(Node.prototype,"removeChild",function(b){var c=m(b),e=ra.call(this,b);c&&a.a(b);return e});p(Node.prototype,"replaceChild",function(b,d){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=bb.call(this,b,d);if(m(this))for(a.a(d),d=0;d<c.length;d++)a.b(c[d]);
return b}c=m(b);var f=bb.call(this,b,d),l=m(this);l&&a.a(d);c&&a.a(b);l&&a.b(b);return f});ua&&ua.get?b(Node.prototype,ua):a.w(function(a){b(a,{enumerable:!0,configurable:!0,get:function(){for(var a=[],b=0;b<this.childNodes.length;b++)a.push(this.childNodes[b].textContent);return a.join("")},set:function(a){for(;this.firstChild;)ra.call(this,this.firstChild);Y.call(this,document.createTextNode(a))}})})}function ac(a){p(Document.prototype,"createElement",function(b){if(this.__CE_hasRegistry){var c=
a.c(b);if(c)return new c.constructor}b=qa.call(this,b);a.g(b);return b});p(Document.prototype,"importNode",function(b,c){b=bc.call(this,b,c);this.__CE_hasRegistry?a.f(b):a.l(b);return b});p(Document.prototype,"createElementNS",function(b,c){if(this.__CE_hasRegistry&&(null===b||"http://www.w3.org/1999/xhtml"===b)){var d=a.c(c);if(d)return new d.constructor}b=cc.call(this,b,c);a.g(b);return b});ta(a,Document.prototype,{V:dc,append:ec})}function ta(a,b,c){function d(b){return function(c){for(var d=[],
e=0;e<arguments.length;++e)d[e-0]=arguments[e];e=[];for(var f=[],g=0;g<d.length;g++){var n=d[g];n instanceof Element&&m(n)&&f.push(n);if(n instanceof DocumentFragment)for(n=n.firstChild;n;n=n.nextSibling)e.push(n);else e.push(n)}b.apply(this,d);for(d=0;d<f.length;d++)a.a(f[d]);if(m(this))for(d=0;d<e.length;d++)f=e[d],f instanceof Element&&a.b(f)}}void 0!==c.V&&(b.prepend=d(c.V));void 0!==c.append&&(b.append=d(c.append))}function fc(a){window.HTMLElement=function(){function b(){var b=this.constructor,
d=a.H(b);if(!d)throw Error("The custom element being constructed was not registered with `customElements`.");var e=d.constructionStack;if(0===e.length)return e=qa.call(document,d.localName),Object.setPrototypeOf(e,b.prototype),e.__CE_state=1,e.__CE_definition=d,a.g(e),e;d=e.length-1;var f=e[d];if(f===cb)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");e[d]=cb;Object.setPrototypeOf(f,b.prototype);a.g(f);return f}b.prototype=gc.prototype;
return b}()}function y(a){this.c=!1;this.a=a;this.h=new Map;this.f=function(a){return a()};this.b=!1;this.g=[];this.i=new va(a,document)}function db(){var a=this;this.b=this.a=void 0;this.c=new Promise(function(b){a.b=b;a.a&&b(a.a)})}function va(a,b){this.c=a;this.a=b;this.b=void 0;this.c.f(this.a);"loading"===this.a.readyState&&(this.b=new MutationObserver(this.g.bind(this)),this.b.observe(this.a,{childList:!0,subtree:!0}))}function z(){this.u=new Map;this.s=new Map;this.j=[];this.h=!1}function J(a,
b){M[N]=a;M[N+1]=b;N+=2;2===N&&(wa?wa(O):hc())}function ic(){return function(){return process.Wa(O)}}function jc(){return"undefined"!==typeof xa?function(){xa(O)}:ya()}function kc(){var a=0,b=new eb(O),c=document.createTextNode("");b.observe(c,{characterData:!0});return function(){c.data=a=++a%2}}function lc(){var a=new MessageChannel;a.port1.onmessage=O;return function(){return a.port2.postMessage(0)}}function ya(){var a=setTimeout;return function(){return a(O,1)}}function O(){for(var a=0;a<N;a+=
2)(0,M[a])(M[a+1]),M[a]=void 0,M[a+1]=void 0;N=0}function mc(){try{var a=require("vertx");xa=a.Ya||a.Xa;return jc()}catch(b){return ya()}}function za(a,b){var c=this,d=new this.constructor(P);void 0===d[aa]&&fb(d);var e=c.o;if(e){var f=arguments[e-1];J(function(){return gb(e,d,f,c.m)})}else Aa(c,d,a,b);return d}function Ba(a){if(a&&"object"===typeof a&&a.constructor===this)return a;var b=new this(P);T(b,a);return b}function P(){}function hb(a){try{return a.then}catch(b){return U.error=b,U}}function nc(a,
b,c,d){try{a.call(b,c,d)}catch(e){return e}}function oc(a,b,c){J(function(a){var d=!1,f=nc(c,b,function(c){d||(d=!0,b!==c?T(a,c):F(a,c))},function(b){d||(d=!0,u(a,b))});!d&&f&&(d=!0,u(a,f))},a)}function pc(a,b){1===b.o?F(a,b.m):2===b.o?u(a,b.m):Aa(b,void 0,function(b){return T(a,b)},function(b){return u(a,b)})}function ib(a,b,c){b.constructor===a.constructor&&c===za&&b.constructor.resolve===Ba?pc(a,b):c===U?(u(a,U.error),U.error=null):void 0===c?F(a,b):"function"===typeof c?oc(a,b,c):F(a,b)}function T(a,
b){if(a===b)u(a,new TypeError("You cannot resolve a promise with itself"));else{var c=typeof b;null===b||"object"!==c&&"function"!==c?F(a,b):ib(a,b,hb(b))}}function qc(a){a.ka&&a.ka(a.m);Ca(a)}function F(a,b){void 0===a.o&&(a.m=b,a.o=1,0!==a.P.length&&J(Ca,a))}function u(a,b){void 0===a.o&&(a.o=2,a.m=b,J(qc,a))}function Aa(a,b,c,d){var e=a.P,f=e.length;a.ka=null;e[f]=b;e[f+1]=c;e[f+2]=d;0===f&&a.o&&J(Ca,a)}function Ca(a){var b=a.P,c=a.o;if(0!==b.length){for(var d,e,f=a.m,l=0;l<b.length;l+=3)d=b[l],
e=b[l+c],d?gb(c,d,e,f):e(f);a.P.length=0}}function jb(){this.error=null}function gb(a,b,c,d){var e="function"===typeof c;if(e){try{var f=c(d)}catch(Sb){Da.error=Sb,f=Da}if(f===Da){var l=!0;var h=f.error;f.error=null}else var g=!0;if(b===f){u(b,new TypeError("A promises callback cannot return that same promise."));return}}else f=d,g=!0;void 0===b.o&&(e&&g?T(b,f):l?u(b,h):1===a?F(b,f):2===a&&u(b,f))}function rc(a,b){try{b(function(b){T(a,b)},function(b){u(a,b)})}catch(c){u(a,c)}}function fb(a){a[aa]=
kb++;a.o=void 0;a.m=void 0;a.P=[]}function V(a,b){this.Ca=a;this.F=new a(P);this.F[aa]||fb(this.F);lb(b)?(this.T=this.length=b.length,this.m=Array(this.length),0===this.length?F(this.F,this.m):(this.length=this.length||0,this.Ba(b),0===this.T&&F(this.F,this.m))):u(this.F,Error("Array Methods must be provided an Array"))}function A(a){this[aa]=kb++;this.m=this.o=void 0;this.P=[];if(P!==a){if("function"!==typeof a)throw new TypeError("You must pass a resolver function as the first argument to the promise constructor");
if(this instanceof A)rc(this,a);else throw new TypeError("Failed to construct 'Promise': Please use the 'new' operator, this object constructor cannot be called as a function.");}}function mb(a){var b=sc.has(a);a=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(a);return!b&&a}function m(a){var b=a.isConnected;if(void 0!==b)return b;for(;a&&!(a.__CE_isImportDocument||a instanceof Document);)a=a.parentNode||(window.ShadowRoot&&a instanceof ShadowRoot?a.host:void 0);return!(!a||!(a.__CE_isImportDocument||a instanceof
Document))}function Ea(a,b){for(;b&&b!==a&&!b.nextSibling;)b=b.parentNode;return b&&b!==a?b.nextSibling:null}function I(a,b,c){c=c?c:new Set;for(var d=a;d;){if(d.nodeType===Node.ELEMENT_NODE){var e=d;b(e);var f=e.localName;if("link"===f&&"import"===e.getAttribute("rel")){d=e.import;if(d instanceof Node&&!c.has(d))for(c.add(d),d=d.firstChild;d;d=d.nextSibling)I(d,b,c);d=Ea(a,e);continue}else if("template"===f){d=Ea(a,e);continue}if(e=e.__CE_shadowRoot)for(e=e.firstChild;e;e=e.nextSibling)I(e,b,c)}d=
d.firstChild?d.firstChild:Ea(a,d)}}function p(a,b,c){a[b]=c}function Fa(a){a=a.replace(D.Fa,"").replace(D.port,"");var b=nb,c=a,d=new na;d.start=0;d.end=c.length;for(var e=d,f=0,l=c.length;f<l;f++)if("{"===c[f]){e.rules||(e.rules=[]);var h=e,g=h.rules[h.rules.length-1]||null;e=new na;e.start=f+1;e.parent=h;e.previous=g;h.rules.push(e)}else"}"===c[f]&&(e.end=f+1,e=e.parent||d);return b(d,a)}function nb(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?
a.previous.end:a.parent.start,a.start-1),c=tc(c),c=c.replace(D.pa," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=G.MEDIA_RULE:c.match(D.Ja)&&(a.type=G.$,a.keyframesName=a.selector.split(D.pa).pop()):a.type=0===c.indexOf("--")?G.ha:G.STYLE_RULE);if(c=a.rules)for(var d=0,e=c.length,f;d<e&&(f=c[d]);d++)nb(f,b);return a}function tc(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(a,c){a=c;for(c=6-
a.length;c--;)a="0"+a;return"\\"+a})}function ob(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===f.selector.indexOf("--"));if(f){f=0;for(var l=e.length,h;f<l&&(h=e[f]);f++)d=ob(h,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(D.la,"").replace(D.oa,""),b=b.replace(D.Ka,"").replace(D.Na,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}function pb(a){w=a&&a.shimcssproperties?
!1:x||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}function Q(a,b){if(!a)return"";"string"===typeof a&&(a=Fa(a));b&&R(a,b);return ob(a,w)}function ba(a){!a.__cssRules&&a.textContent&&(a.__cssRules=Fa(a.textContent));return a.__cssRules||null}function qb(a){return!!a.parent&&a.parent.type===G.$}function R(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===G.MEDIA_RULE){var l=a.selector.match(uc);l&&(window.matchMedia(l[1]).matches||
(e=!0))}f===G.STYLE_RULE?b(a):c&&f===G.$?c(a):f===G.ha&&(e=!0);if((a=a.rules)&&!e){e=0;f=a.length;for(var h;e<f&&(h=a[e]);e++)R(h,b,c,d)}}}function Ga(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;rb(e,c,d);return e}function rb(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);K?a.compareDocumentPosition(K)===Node.DOCUMENT_POSITION_PRECEDING&&(K=a):K=a}function sb(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");a:{var d=
0;var e=c+3;for(var f=a.length;e<f;e++)if("("===a[e])d++;else if(")"===a[e]&&0===--d)break a;e=-1}d=a.substring(c+4,e);c=a.substring(0,c);a=sb(a.substring(e+1),b);e=d.indexOf(",");return-1===e?b(c,d.trim(),"",a):b(c,d.substring(0,e).trim(),d.substring(e+1).trim(),a)}function ca(a,b){x?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}function L(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);
return{is:b,R:c}}function tb(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode();var l=e;var h=[];l.classList?h=Array.from(l.classList):l instanceof window.SVGElement&&l.hasAttribute("class")&&(h=l.getAttribute("class").split(/\s+/));l=h;h=l.indexOf(v.c);(l=-1<h?l[h+1]:"")&&f===e.ownerDocument?v.a(e,l,!0):f.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&
(f=f.host)&&(f=L(f).is,l!==f&&(l&&v.a(e,l,!0),v.a(e,f)))}}}}function vc(a){if(a=da[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function ub(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function wc(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a.b||(a.b=!0,xc.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a.b=!1}))}function Ra(a){requestAnimationFrame(function(){vb?
vb(a):(Ha||(Ha=new Promise(function(a){Ia=a}),"complete"===document.readyState?Ia():document.addEventListener("readystatechange",function(){"complete"===document.readyState&&Ia()})),Ha.then(function(){a&&a()}))})}(function(){if(!function(){var a=document.createEvent("Event");a.initEvent("foo",!0,!0);a.preventDefault();return a.defaultPrevented}()){var a=Event.prototype.preventDefault;Event.prototype.preventDefault=function(){this.cancelable&&(a.call(this),Object.defineProperty(this,"defaultPrevented",
{get:function(){return!0},configurable:!0}))}}var b=/Trident/.test(navigator.userAgent);if(!window.CustomEvent||b&&"function"!==typeof window.CustomEvent)window.CustomEvent=function(a,b){b=b||{};var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c},window.CustomEvent.prototype=window.Event.prototype;if(!window.Event||b&&"function"!==typeof window.Event){var c=window.Event;window.Event=function(a,b){b=b||{};var c=document.createEvent("Event");
c.initEvent(a,!!b.bubbles,!!b.cancelable);return c};if(c)for(var d in c)window.Event[d]=c[d];window.Event.prototype=c.prototype}if(!window.MouseEvent||b&&"function"!==typeof window.MouseEvent){b=window.MouseEvent;window.MouseEvent=function(a,b){b=b||{};var c=document.createEvent("MouseEvent");c.initMouseEvent(a,!!b.bubbles,!!b.cancelable,b.view||window,b.detail,b.screenX,b.screenY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget);return c};if(b)for(d in b)window.MouseEvent[d]=
b[d];window.MouseEvent.prototype=b.prototype}Array.from||(Array.from=function(a){return[].slice.call(a)});Object.assign||(Object.assign=function(a,b){for(var c=[].slice.call(arguments,1),d=0,e;d<c.length;d++)if(e=c[d])for(var f=a,g=e,k=Object.getOwnPropertyNames(g),m=0;m<k.length;m++)e=k[m],f[e]=g[e];return a})})(window.WebComponents);(function(){function a(){}var b="undefined"===typeof HTMLTemplateElement;/Trident/.test(navigator.userAgent)&&function(){var a=Document.prototype.importNode;Document.prototype.importNode=
function(){var b=a.apply(this,arguments);if(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE){var c=this.createDocumentFragment();c.appendChild(b);return c}return b}}();var c=Node.prototype.cloneNode,d=Document.prototype.createElement,e=Document.prototype.importNode,f=function(){if(!b){var a=document.createElement("template"),c=document.createElement("template");c.content.appendChild(document.createElement("div"));a.content.appendChild(c);a=a.cloneNode(!0);return 0===a.content.childNodes.length||0===a.content.firstChild.content.childNodes.length||
!(document.createDocumentFragment().cloneNode()instanceof DocumentFragment)}}();if(b){var l=function(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case "\u00a0":return"&nbsp;"}},g=function(b){Object.defineProperty(b,"innerHTML",{get:function(){for(var a="",b=this.content.firstChild;b;b=b.nextSibling)a+=b.outerHTML||b.data.replace(t,l);return a},set:function(b){q.body.innerHTML=b;for(a.b(q);this.content.firstChild;)this.content.removeChild(this.content.firstChild);
for(;q.body.firstChild;)this.content.appendChild(q.body.firstChild)},configurable:!0})},q=document.implementation.createHTMLDocument("template"),k=!0,n=document.createElement("style");n.textContent="template{display:none;}";var m=document.head;m.insertBefore(n,m.firstElementChild);a.prototype=Object.create(HTMLElement.prototype);var r=!document.createElement("div").hasOwnProperty("innerHTML");a.J=function(b){if(!b.content){b.content=q.createDocumentFragment();for(var c;c=b.firstChild;)b.content.appendChild(c);
if(r)b.__proto__=a.prototype;else if(b.cloneNode=function(b){return a.a(this,b)},k)try{g(b)}catch(Rc){k=!1}a.b(b.content)}};g(a.prototype);a.b=function(b){b=b.querySelectorAll("template");for(var c=0,d=b.length,e;c<d&&(e=b[c]);c++)a.J(e)};document.addEventListener("DOMContentLoaded",function(){a.b(document)});Document.prototype.createElement=function(){var b=d.apply(this,arguments);"template"===b.localName&&a.J(b);return b};var t=/[&\u00A0<>]/g}if(b||f)a.a=function(a,b){var d=c.call(a,!1);this.J&&
this.J(d);b&&(d.content.appendChild(c.call(a.content,!0)),this.ea(d.content,a.content));return d},a.prototype.cloneNode=function(b){return a.a(this,b)},a.ea=function(a,b){if(b.querySelectorAll){b=b.querySelectorAll("template");a=a.querySelectorAll("template");for(var c=0,d=a.length,e,f;c<d;c++)f=b[c],e=a[c],this.J&&this.J(f),e.parentNode.replaceChild(f.cloneNode(!0),e)}},Node.prototype.cloneNode=function(b){if(this instanceof DocumentFragment)if(b)var d=this.ownerDocument.importNode(this,!0);else return this.ownerDocument.createDocumentFragment();
else d=c.call(this,b);b&&a.ea(d,this);return d},Document.prototype.importNode=function(b,c){if("template"===b.localName)return a.a(b,c);var d=e.call(this,b,c);c&&a.ea(d,b);return d},f&&(window.HTMLTemplateElement.prototype.cloneNode=function(b){return a.a(this,b)});b&&(window.HTMLTemplateElement=a)})();var Ja;Array.isArray?Ja=Array.isArray:Ja=function(a){return"[object Array]"===Object.prototype.toString.call(a)};var lb=Ja,N=0,xa,wa,wb="undefined"!==typeof window?window:void 0,xb=wb||{},eb=xb.MutationObserver||
xb.WebKitMutationObserver,yc="undefined"!==typeof Uint8ClampedArray&&"undefined"!==typeof importScripts&&"undefined"!==typeof MessageChannel,M=Array(1E3);var hc="undefined"===typeof self&&"undefined"!==typeof process&&"[object process]"==={}.toString.call(process)?ic():eb?kc():yc?lc():wb||"function"!==typeof require?ya():mc();var aa=Math.random().toString(36).substring(16),U=new jb,Da=new jb,kb=0;V.prototype.Ba=function(a){for(var b=0;void 0===this.o&&b<a.length;b++)this.Aa(a[b],b)};V.prototype.Aa=
function(a,b){var c=this.Ca,d=c.resolve;d===Ba?(d=hb(a),d===za&&void 0!==a.o?this.ba(a.o,b,a.m):"function"!==typeof d?(this.T--,this.m[b]=a):c===A?(c=new c(P),ib(c,a,d),this.ca(c,b)):this.ca(new c(function(b){return b(a)}),b)):this.ca(d(a),b)};V.prototype.ba=function(a,b,c){var d=this.F;void 0===d.o&&(this.T--,2===a?u(d,c):this.m[b]=c);0===this.T&&F(d,this.m)};V.prototype.ca=function(a,b){var c=this;Aa(a,void 0,function(a){return c.ba(1,b,a)},function(a){return c.ba(2,b,a)})};A.all=function(a){return(new V(this,
a)).F};A.race=function(a){var b=this;return lb(a)?new b(function(c,d){for(var e=a.length,f=0;f<e;f++)b.resolve(a[f]).then(c,d)}):new b(function(a,b){return b(new TypeError("You must pass an array to race."))})};A.resolve=Ba;A.reject=function(a){var b=new this(P);u(b,a);return b};A.Ua=function(a){wa=a};A.Ta=function(a){J=a};A.Qa=J;A.prototype={constructor:A,then:za,a:function(a){return this.then(null,a)}};window.Promise||(window.Promise=A,A.prototype["catch"]=A.prototype.a);(function(a){function b(a,
b){if("function"===typeof window.CustomEvent)return new CustomEvent(a,b);var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c}function c(a){if(n)return a.ownerDocument!==document?a.ownerDocument:null;var b=a.__importDoc;if(!b&&a.parentNode){b=a.parentNode;if("function"===typeof b.closest)b=b.closest("link[rel=import]");else for(;!g(b)&&(b=b.parentNode););a.__importDoc=b}return b}function d(a){var b=document.querySelectorAll("link[rel=import]:not(import-dependency)"),
c=b.length;c?k(b,function(b){return l(b,function(){0===--c&&a()})}):a()}function e(a){function b(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",b),a())}document.addEventListener("readystatechange",b);b()}function f(a){e(function(){return d(function(){return a&&a()})})}function l(a,b){if(a.__loaded)b&&b();else if("script"===a.localName&&!a.src||"style"===a.localName&&!a.firstChild)a.__loaded=!0,b&&b();else{var c=function(d){a.removeEventListener(d.type,
c);a.__loaded=!0;b&&b()};a.addEventListener("load",c);w&&"style"===a.localName||a.addEventListener("error",c)}}function g(a){return a.nodeType===Node.ELEMENT_NODE&&"link"===a.localName&&"import"===a.rel}function q(){var a=this;this.a={};this.b=0;this.f=new MutationObserver(function(b){return a.l(b)});this.f.observe(document.head,{childList:!0,subtree:!0});this.c(document)}function k(a,b,c){var d=a?a.length:0,e=c?-1:1;for(c=c?d-1:0;c<d&&0<=c;c+=e)b(a[c],c)}var n="import"in document.createElement("link"),
m=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",{get:function(){return m||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var r=/(^\/)|(^#)|(^[\w-\d]*:)/,t=/(url\()([^)]*)(\))/g,v=/(@import[\s]+(?!url\())([^;]*)(;)/g,x=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,p={Ga:function(a,b){a.href&&a.setAttribute("href",p.ga(a.getAttribute("href"),b));a.src&&a.setAttribute("src",p.ga(a.getAttribute("src"),b));
if("style"===a.localName){var c=p.qa(a.textContent,b,t);a.textContent=p.qa(c,b,v)}},qa:function(a,b,c){return a.replace(c,function(a,c,d,e){a=d.replace(/["']/g,"");b&&(a=p.ra(a,b));return c+"'"+a+"'"+e})},ga:function(a,b){return a&&r.test(a)?a:p.ra(a,b)},ra:function(a,b){if(void 0===p.aa){p.aa=!1;try{var c=new URL("b","http://a");c.pathname="c%20d";p.aa="http://a/c%20d"===c.href}catch(Sc){}}if(p.aa)return(new URL(a,b)).href;c=p.za;c||(c=document.implementation.createHTMLDocument("temp"),p.za=c,c.ja=
c.createElement("base"),c.head.appendChild(c.ja),c.ia=c.createElement("a"));c.ja.href=b;c.ia.href=a;return c.ia.href||a}},y={async:!0,load:function(a,b,c){if(a)if(a.match(/^data:/)){a=a.split(",");var d=a[1];d=-1<a[0].indexOf(";base64")?atob(d):decodeURIComponent(d);b(d)}else{var e=new XMLHttpRequest;e.open("GET",a,y.async);e.onload=function(){var a=e.responseURL||e.getResponseHeader("Location");a&&0===a.indexOf("/")&&(a=(location.origin||location.protocol+"//"+location.host)+a);var d=e.response||
e.responseText;304===e.status||0===e.status||200<=e.status&&300>e.status?b(d,a):c(d)};e.send()}else c("error: href must be specified")}},w=/Trident/.test(navigator.userAgent)||/Edge\/\d./i.test(navigator.userAgent);q.prototype.c=function(a){var b=this;k(a.querySelectorAll("link[rel=import]"),function(a){return b.h(a)})};q.prototype.h=function(a){var b=this,c=a.href;if(void 0!==this.a[c]){var d=this.a[c];d&&d.__loaded&&(a.import=d,this.g(a))}else this.b++,this.a[c]="pending",y.load(c,function(a,d){a=
b.s(a,d||c);b.a[c]=a;b.b--;b.c(a);b.i()},function(){b.a[c]=null;b.b--;b.i()})};q.prototype.s=function(a,b){if(!a)return document.createDocumentFragment();w&&(a=a.replace(x,function(a,b,c){return-1===a.indexOf("type=")?b+" type=import-disable "+c:a}));var c=document.createElement("template");c.innerHTML=a;if(c.content)a=c.content;else for(a=document.createDocumentFragment();c.firstChild;)a.appendChild(c.firstChild);if(c=a.querySelector("base"))b=p.ga(c.getAttribute("href"),b),c.removeAttribute("href");
var d=0;k(a.querySelectorAll('link[rel=import], link[rel=stylesheet][href][type=import-disable],\n    style:not([type]), link[rel=stylesheet][href]:not([type]),\n    script:not([type]), script[type="application/javascript"],\n    script[type="text/javascript"]'),function(a){l(a);p.Ga(a,b);a.setAttribute("import-dependency","");"script"===a.localName&&!a.src&&a.textContent&&(a.setAttribute("src","data:text/javascript;charset=utf-8,"+encodeURIComponent(a.textContent+("\n//# sourceURL="+b+(d?"-"+d:"")+
".js\n"))),a.textContent="",d++)});return a};q.prototype.i=function(){var a=this;if(!this.b){this.f.disconnect();this.flatten(document);var b=!1,c=!1,d=function(){c&&b&&(a.c(document),a.b||(a.f.observe(document.head,{childList:!0,subtree:!0}),a.j()))};this.w(function(){c=!0;d()});this.u(function(){b=!0;d()})}};q.prototype.flatten=function(a){var b=this;k(a.querySelectorAll("link[rel=import]"),function(a){var c=b.a[a.href];(a.import=c)&&c.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(b.a[a.href]=a,a.readyState=
"loading",a.import=a,b.flatten(c),a.appendChild(c))})};q.prototype.u=function(a){function b(e){if(e<d){var f=c[e],g=document.createElement("script");f.removeAttribute("import-dependency");k(f.attributes,function(a){return g.setAttribute(a.name,a.value)});m=g;f.parentNode.replaceChild(g,f);l(g,function(){m=null;b(e+1)})}else a()}var c=document.querySelectorAll("script[import-dependency]"),d=c.length;b(0)};q.prototype.w=function(a){var b=document.querySelectorAll("style[import-dependency],\n    link[rel=stylesheet][import-dependency]"),
d=b.length;if(d){var e=w&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");k(b,function(b){l(b,function(){b.removeAttribute("import-dependency");0===--d&&a()});if(e&&b.parentNode!==document.head){var f=document.createElement(b.localName);f.__appliedElement=b;f.setAttribute("type","import-placeholder");b.parentNode.insertBefore(f,b.nextSibling);for(f=c(b);f&&c(f);)f=c(f);f.parentNode!==document.head&&(f=null);document.head.insertBefore(b,f);b.removeAttribute("type")}})}else a()};
q.prototype.j=function(){var a=this;k(document.querySelectorAll("link[rel=import]"),function(b){return a.g(b)},!0)};q.prototype.g=function(a){a.__loaded||(a.__loaded=!0,a.import&&(a.import.readyState="complete"),a.dispatchEvent(b(a.import?"load":"error",{bubbles:!1,cancelable:!1,detail:void 0})))};q.prototype.l=function(a){var b=this;k(a,function(a){return k(a.addedNodes,function(a){a&&a.nodeType===Node.ELEMENT_NODE&&(g(a)?b.h(a):b.c(a))})})};if(n){k(document.querySelectorAll("link[rel=import]"),
function(a){a.import&&"loading"===a.import.readyState||(a.__loaded=!0)});var z=function(a){a=a.target;g(a)&&(a.__loaded=!0)};document.addEventListener("load",z,!0);document.addEventListener("error",z,!0)}else{var u=Object.getOwnPropertyDescriptor(Node.prototype,"baseURI");Object.defineProperty((!u||u.configurable?Node:Element).prototype,"baseURI",{get:function(){var a=g(this)?this:c(this);return a?a.href:u&&u.get?u.get.call(this):(document.querySelector("base")||window.location).href},configurable:!0,
enumerable:!0});e(function(){return new q})}f(function(){return document.dispatchEvent(b("HTMLImportsLoaded",{cancelable:!0,bubbles:!0,detail:void 0}))});a.useNative=n;a.whenReady=f;a.importForElement=c})(window.HTMLImports=window.HTMLImports||{});window.WebComponents=window.WebComponents||{flags:{}};var yb=document.querySelector('script[src*="webcomponents-lite.js"]'),zc=/wc-(.+)/,B={};if(!B.noOpts){location.search.slice(1).split("&").forEach(function(a){a=a.split("=");var b;a[0]&&(b=a[0].match(zc))&&
(B[b[1]]=a[1]||!0)});if(yb)for(var zb=0,ea;ea=yb.attributes[zb];zb++)"src"!==ea.name&&(B[ea.name]=ea.value||!0);if(B.log&&B.log.split){var Ac=B.log.split(",");B.log={};Ac.forEach(function(a){B.log[a]=!0})}else B.log={}}window.WebComponents.flags=B;var Ab=B.shadydom;Ab&&(window.ShadyDOM=window.ShadyDOM||{},window.ShadyDOM.force=Ab);var Bb=B.register||B.ce;Bb&&window.customElements&&(window.customElements.forcePolyfill=Bb);var sc=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));
z.prototype.I=function(a,b){this.u.set(a,b);this.s.set(b.constructor,b)};z.prototype.c=function(a){return this.u.get(a)};z.prototype.H=function(a){return this.s.get(a)};z.prototype.w=function(a){this.h=!0;this.j.push(a)};z.prototype.l=function(a){var b=this;this.h&&I(a,function(a){return b.g(a)})};z.prototype.g=function(a){if(this.h&&!a.__CE_patched){a.__CE_patched=!0;for(var b=0;b<this.j.length;b++)this.j[b](a)}};z.prototype.b=function(a){var b=[];I(a,function(a){return b.push(a)});for(a=0;a<b.length;a++){var c=
b[a];1===c.__CE_state?this.connectedCallback(c):this.i(c)}};z.prototype.a=function(a){var b=[];I(a,function(a){return b.push(a)});for(a=0;a<b.length;a++){var c=b[a];1===c.__CE_state&&this.disconnectedCallback(c)}};z.prototype.f=function(a,b){var c=this;b=b?b:{};var d=b.Oa||new Set,e=b.sa||function(a){return c.i(a)},f=[];I(a,function(a){if("link"===a.localName&&"import"===a.getAttribute("rel")){var b=a.import;b instanceof Node&&"complete"===b.readyState?(b.__CE_isImportDocument=!0,b.__CE_hasRegistry=
!0):a.addEventListener("load",function(){var b=a.import;if(!b.__CE_documentLoadHandled){b.__CE_documentLoadHandled=!0;b.__CE_isImportDocument=!0;b.__CE_hasRegistry=!0;var f=new Set(d);f.delete(b);c.f(b,{Oa:f,sa:e})}})}else f.push(a)},d);if(this.h)for(a=0;a<f.length;a++)this.g(f[a]);for(a=0;a<f.length;a++)e(f[a])};z.prototype.i=function(a){if(void 0===a.__CE_state){var b=this.c(a.localName);if(b){b.constructionStack.push(a);var c=b.constructor;try{try{if(new c!==a)throw Error("The custom element constructor did not produce the element being upgraded.");
}finally{b.constructionStack.pop()}}catch(f){throw a.__CE_state=2,f;}a.__CE_state=1;a.__CE_definition=b;if(b.attributeChangedCallback)for(b=b.observedAttributes,c=0;c<b.length;c++){var d=b[c],e=a.getAttribute(d);null!==e&&this.attributeChangedCallback(a,d,null,e,null)}m(a)&&this.connectedCallback(a)}}};z.prototype.connectedCallback=function(a){var b=a.__CE_definition;b.connectedCallback&&b.connectedCallback.call(a)};z.prototype.disconnectedCallback=function(a){var b=a.__CE_definition;b.disconnectedCallback&&
b.disconnectedCallback.call(a)};z.prototype.attributeChangedCallback=function(a,b,c,d,e){var f=a.__CE_definition;f.attributeChangedCallback&&-1<f.observedAttributes.indexOf(b)&&f.attributeChangedCallback.call(a,b,c,d,e)};va.prototype.f=function(){this.b&&this.b.disconnect()};va.prototype.g=function(a){var b=this.a.readyState;"interactive"!==b&&"complete"!==b||this.f();for(b=0;b<a.length;b++)for(var c=a[b].addedNodes,d=0;d<c.length;d++)this.c.f(c[d])};db.prototype.resolve=function(a){if(this.a)throw Error("Already resolved.");
this.a=a;this.b&&this.b(a)};y.prototype.define=function(a,b){var c=this;if(!(b instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!mb(a))throw new SyntaxError("The element name '"+a+"' is not valid.");if(this.a.c(a))throw Error("A custom element with name '"+a+"' has already been defined.");if(this.c)throw Error("A custom element is already being defined.");this.c=!0;try{var d=function(a){var b=e[a];if(void 0!==b&&!(b instanceof Function))throw Error("The '"+
a+"' callback must be a function.");return b},e=b.prototype;if(!(e instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var f=d("connectedCallback");var g=d("disconnectedCallback");var h=d("adoptedCallback");var q=d("attributeChangedCallback");var k=b.observedAttributes||[]}catch(n){return}finally{this.c=!1}b={localName:a,constructor:b,connectedCallback:f,disconnectedCallback:g,adoptedCallback:h,attributeChangedCallback:q,observedAttributes:k,constructionStack:[]};
this.a.I(a,b);this.g.push(b);this.b||(this.b=!0,this.f(function(){return c.j()}))};y.prototype.j=function(){var a=this;if(!1!==this.b){this.b=!1;for(var b=this.g,c=[],d=new Map,e=0;e<b.length;e++)d.set(b[e].localName,[]);this.a.f(document,{sa:function(b){if(void 0===b.__CE_state){var e=b.localName,f=d.get(e);f?f.push(b):a.a.c(e)&&c.push(b)}}});for(e=0;e<c.length;e++)this.a.i(c[e]);for(;0<b.length;){var f=b.shift();e=f.localName;f=d.get(f.localName);for(var g=0;g<f.length;g++)this.a.i(f[g]);(e=this.h.get(e))&&
e.resolve(void 0)}}};y.prototype.get=function(a){if(a=this.a.c(a))return a.constructor};y.prototype.whenDefined=function(a){if(!mb(a))return Promise.reject(new SyntaxError("'"+a+"' is not a valid custom element name."));var b=this.h.get(a);if(b)return b.c;b=new db;this.h.set(a,b);this.a.c(a)&&!this.g.some(function(b){return b.localName===a})&&b.resolve(void 0);return b.c};y.prototype.l=function(a){this.i.f();var b=this.f;this.f=function(c){return a(function(){return b(c)})}};window.CustomElementRegistry=
y;y.prototype.define=y.prototype.define;y.prototype.get=y.prototype.get;y.prototype.whenDefined=y.prototype.whenDefined;y.prototype.polyfillWrapFlushCallback=y.prototype.l;var qa=window.Document.prototype.createElement,cc=window.Document.prototype.createElementNS,bc=window.Document.prototype.importNode,dc=window.Document.prototype.prepend,ec=window.Document.prototype.append,Bc=window.DocumentFragment.prototype.prepend,Cc=window.DocumentFragment.prototype.append,Ua=window.Node.prototype.cloneNode,
Y=window.Node.prototype.appendChild,ab=window.Node.prototype.insertBefore,ra=window.Node.prototype.removeChild,bb=window.Node.prototype.replaceChild,ua=Object.getOwnPropertyDescriptor(window.Node.prototype,"textContent"),Ta=window.Element.prototype.attachShadow,oa=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),sa=window.Element.prototype.getAttribute,Va=window.Element.prototype.setAttribute,Xa=window.Element.prototype.removeAttribute,Z=window.Element.prototype.getAttributeNS,
Wa=window.Element.prototype.setAttributeNS,Ya=window.Element.prototype.removeAttributeNS,$a=window.Element.prototype.insertAdjacentElement,Tb=window.Element.prototype.prepend,Ub=window.Element.prototype.append,Wb=window.Element.prototype.before,Xb=window.Element.prototype.after,Yb=window.Element.prototype.replaceWith,Zb=window.Element.prototype.remove,gc=window.HTMLElement,pa=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),Za=window.HTMLElement.prototype.insertAdjacentElement,
cb=new function(){},fa=window.customElements;if(!fa||fa.forcePolyfill||"function"!=typeof fa.define||"function"!=typeof fa.get){var S=new z;fc(S);ac(S);ta(S,DocumentFragment.prototype,{V:Bc,append:Cc});$b(S);Rb(S);document.__CE_hasRegistry=!0;var Dc=new y(S);Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:Dc})}var G={STYLE_RULE:1,$:7,MEDIA_RULE:4,ha:1E3},D={Fa:/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,port:/@import[^;]*;/gim,la:/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,
oa:/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,Ka:/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,Na:/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,Ja:/^@[^\s]*keyframes/,pa:/\s+/g},x=!(window.ShadyDOM&&window.ShadyDOM.inUse);if(window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss)var w=window.ShadyCSS.nativeCss;else window.ShadyCSS?(pb(window.ShadyCSS),window.ShadyCSS=void 0):pb(window.WebComponents&&window.WebComponents.flags);var ha=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,
ia=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,Ec=/(--[\w-]+)\s*([:,;)]|$)/gi,Fc=/(animation\s*:)|(animation-name\s*:)/,uc=/@media\s(.*)/,Gc=/\{[^}]*\}/g,K=null;r.prototype.a=function(a,b,c){a.__styleScoped?a.__styleScoped=null:this.i(a,b||"",c)};r.prototype.i=function(a,b,c){a.nodeType===Node.ELEMENT_NODE&&this.H(a,b,c);if(a="template"===a.localName?(a.content||a.Ra).childNodes:a.children||a.childNodes)for(var d=0;d<a.length;d++)this.i(a[d],b,c)};r.prototype.H=function(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),
a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute(Hc);c?d&&(b=d.replace("style-scope","").replace(b,""),ca(a,b)):ca(a,(d?d+" ":"")+"style-scope "+b)}};r.prototype.b=function(a,b,c){var d=a.__cssBuild;x||"shady"===d?b=Q(b,c):(a=L(a),b=this.M(b,a.is,a.R,c)+"\n\n");return b.trim()};r.prototype.M=function(a,b,c,d){var e=this.f(b,c);b=this.h(b);var f=this;return Q(a,function(a){a.c||(f.O(a,b,e),a.c=!0);d&&d(a,b,e)})};r.prototype.h=function(a){return a?
Ic+a:""};r.prototype.f=function(a,b){return b?"[is="+a+"]":a};r.prototype.O=function(a,b,c){this.j(a,this.g,b,c)};r.prototype.j=function(a,b,c,d){a.selector=a.A=this.l(a,b,c,d)};r.prototype.l=function(a,b,c,d){var e=a.selector.split(Cb);if(!qb(a)){a=0;for(var f=e.length,g;a<f&&(g=e[a]);a++)e[a]=b.call(this,g,c,d)}return e.join(Cb)};r.prototype.u=function(a){return a.replace(Ka,function(a,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+
d+")"})};r.prototype.g=function(a,b,c){var d=this,e=!1;a=a.trim();var f=Ka.test(a);f&&(a=a.replace(Ka,function(a,b,c){return":"+b+"("+c.replace(/\s/g,"")+")"}),a=this.u(a));a=a.replace(Jc,La+" $1");a=a.replace(Kc,function(a,f,g){e||(a=d.I(g,f,b,c),e=e||a.stop,f=a.Ea,g=a.value);return f+g});f&&(a=this.u(a));return a};r.prototype.I=function(a,b,c,d){var e=a.indexOf(Ma);0<=a.indexOf(La)?a=this.L(a,d):0!==e&&(a=c?this.s(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(Lc,function(a,b){return" > "+
b}))}a=a.replace(Mc,function(a,b,c){return'[dir="'+c+'"] '+b+", "+b+'[dir="'+c+'"]'});return{value:a,Ea:b,stop:f}};r.prototype.s=function(a,b){a=a.split(Db);a[0]+=b;return a.join(Db)};r.prototype.L=function(a,b){var c=a.match(Eb);return(c=c&&c[2].trim()||"")?c[0].match(Fb)?a.replace(Eb,function(a,c,f){return b+f}):c.split(Fb)[0]===b?c:Nc:a.replace(La,b)};r.prototype.N=function(a){a.selector=a.parsedSelector;this.w(a);this.j(a,this.S)};r.prototype.w=function(a){a.selector===Oc&&(a.selector="html")};
r.prototype.S=function(a){return a.match(Ma)?this.g(a,Gb):this.s(a.trim(),Gb)};Qa.Object.defineProperties(r.prototype,{c:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});var Ka=/:(nth[-\w]+)\(([^)]+)\)/,Gb=":not(.style-scope)",Cb=",",Kc=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,Fb=/[[.:#*]/,La=":host",Oc=":root",Ma="::slotted",Jc=new RegExp("^("+Ma+")"),Eb=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Lc=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Mc=/(.*):dir\((?:(ltr|rtl))\)/,
Ic=".",Db=":",Hc="class",Nc="should_not_match",v=new r;t.get=function(a){return a?a.__styleInfo:null};t.set=function(a,b){return a.__styleInfo=b};t.prototype.c=function(){return this.D};t.prototype._getStyleRules=t.prototype.c;var Hb=function(a){return a.matches||a.matchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector||a.webkitMatchesSelector}(window.Element.prototype),Pc=navigator.userAgent.match("Trident");k.prototype.N=function(a){var b=this,c={},d=[],e=0;R(a,function(a){b.c(a);
a.index=e++;b.M(a.v.cssText,c)},function(a){d.push(a)});a.b=d;a=[];for(var f in c)a.push(f);return a};k.prototype.c=function(a){if(!a.v){var b={},c={};this.b(a,c)&&(b.C=c,a.rules=null);b.cssText=this.L(a);a.v=b}};k.prototype.b=function(a,b){var c=a.v;if(c){if(c.C)return Object.assign(b,c.C),!0}else{c=a.parsedCssText;for(var d;a=ha.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}};k.prototype.L=function(a){return this.S(a.parsedCssText)};k.prototype.S=function(a){return a.replace(Gc,
"").replace(ha,"")};k.prototype.M=function(a,b){for(var c;c=Ec.exec(a);){var d=c[1];":"!==c[2]&&(b[d]=!0)}};k.prototype.X=function(a){for(var b=Object.getOwnPropertyNames(a),c=0,d;c<b.length;c++)d=b[c],a[d]=this.a(a[d],a)};k.prototype.a=function(a,b){if(a)if(0<=a.indexOf(";"))a=this.f(a,b);else{var c=this;a=sb(a,function(a,e,f,g){if(!e)return a+g;(e=c.a(b[e],b))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=c.a(b[f]||f,b)||f;return a+(e||"")+g})}return a&&a.trim()||""};k.prototype.f=function(a,
b){a=a.split(";");for(var c=0,d,e;c<a.length;c++)if(d=a[c]){ia.lastIndex=0;if(e=ia.exec(d))d=this.a(b[e[1]],b);else if(e=d.indexOf(":"),-1!==e){var f=d.substring(e);f=f.trim();f=this.a(f,b)||f;d=d.substring(0,e)+f}a[c]=d&&d.lastIndexOf(";")===d.length-1?d.slice(0,-1):d||""}return a.join(";")};k.prototype.I=function(a,b){var c="";a.v||this.c(a);a.v.cssText&&(c=this.f(a.v.cssText,b));a.cssText=c};k.prototype.H=function(a,b){var c=a.cssText,d=a.cssText;null==a.na&&(a.na=Fc.test(c));if(a.na)if(null==
a.U){a.U=[];for(var e in b)d=b[e],d=d(c),c!==d&&(c=d,a.U.push(e))}else{for(e=0;e<a.U.length;++e)d=b[a.U[e]],c=d(c);d=c}a.cssText=d};k.prototype.W=function(a,b){var c={},d=this,e=[];R(a,function(a){a.v||d.c(a);var f=a.A||a.parsedSelector;b&&a.v.C&&f&&Hb.call(b,f)&&(d.b(a,c),a=a.index,f=parseInt(a/32,10),e[f]=(e[f]||0)|1<<a%32)},null,!0);return{C:c,key:e}};k.prototype.Z=function(a,b,c,d){b.v||this.c(b);if(b.v.C){var e=L(a);a=e.is;e=e.R;e=a?v.f(a,e):"html";var f=b.parsedSelector,g=":host > *"===f||"html"===
f,h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),h=!g&&0===f.indexOf(e));"shadow"===c&&(g=":host > *"===f||"html"===f,h=h&&!g);if(g||h)c=e,h&&(x&&!b.A&&(b.A=v.l(b,v.g,v.h(a),e)),c=b.A||e),d({Ma:c,Ia:h,Va:g})}};k.prototype.O=function(a,b){var c={},d={},e=this,f=b&&b.__cssBuild;R(b,function(b){e.Z(a,b,f,function(f){Hb.call(a.Sa||a,f.Ma)&&(f.Ia?e.b(b,c):e.b(b,d))})},null,!0);return{La:d,Ha:c}};k.prototype.Y=function(a,b,c){var d=this,e=L(a),f=v.f(e.is,e.R),g=new RegExp("(?:^|[^.#[:])"+
(a.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])");e=t.get(a).D;var h=this.h(e,c);return v.b(a,e,function(a){d.I(a,b);x||qb(a)||!a.cssText||(d.H(a,h),d.l(a,g,f,c))})};k.prototype.h=function(a,b){a=a.b;var c={};if(!x&&a)for(var d=0,e=a[d];d<a.length;e=a[++d])this.j(e,b),c[e.keyframesName]=this.i(e);return c};k.prototype.i=function(a){return function(b){return b.replace(a.f,a.a)}};k.prototype.j=function(a,b){a.f=new RegExp(a.keyframesName,"g");a.a=a.keyframesName+"-"+b;a.A=a.A||a.selector;a.selector=
a.A.replace(a.keyframesName,a.a)};k.prototype.l=function(a,b,c,d){a.A=a.A||a.selector;d="."+d;for(var e=a.A.split(","),f=0,g=e.length,h;f<g&&(h=e[f]);f++)e[f]=h.match(b)?h.replace(c,d):d+" "+h;a.selector=e.join(",")};k.prototype.u=function(a,b,c){var d=a.getAttribute("class")||"",e=d;c&&(e=d.replace(new RegExp("\\s*x-scope\\s*"+c+"\\s*","g")," "));e+=(e?" ":"")+"x-scope "+b;d!==e&&ca(a,e)};k.prototype.w=function(a,b,c,d){b=d?d.textContent||"":this.Y(a,b,c);var e=t.get(a),f=e.a;f&&!x&&f!==d&&(f._useCount--,
0>=f._useCount&&f.parentNode&&f.parentNode.removeChild(f));x?e.a?(e.a.textContent=b,d=e.a):b&&(d=Ga(b,c,a.shadowRoot,e.b)):d?d.parentNode||(Pc&&-1<b.indexOf("@media")&&(d.textContent=b),rb(d,null,e.b)):b&&(d=Ga(b,c,null,e.b));d&&(d._useCount=d._useCount||0,e.a!=d&&d._useCount++,e.a=d);return d};k.prototype.s=function(a,b){var c=ba(a),d=this;a.textContent=Q(c,function(a){var c=a.cssText=a.parsedCssText;a.v&&a.v.cssText&&(c=c.replace(D.la,"").replace(D.oa,""),a.cssText=d.f(c,b))})};Qa.Object.defineProperties(k.prototype,
{g:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var H=new k,Na={},ja=window.customElements;if(ja&&!x){var Qc=ja.define;ja.define=function(a,b,c){var d=document.createComment(" Shady DOM styles for "+a+" "),e=document.head;e.insertBefore(d,(K?K.nextSibling:null)||e.firstChild);K=d;Na[a]=d;return Qc.call(ja,a,b,c)}}X.prototype.b=function(a,b,c){for(var d=0;d<c.length;d++){var e=c[d];if(a.C[e]!==b[e])return!1}return!0};X.prototype.c=function(a,b,c,d){var e=this.cache[a]||[];e.push({C:b,
styleElement:c,B:d});e.length>this.f&&e.shift();this.cache[a]=e};X.prototype.a=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d];if(this.b(e,b,c))return e}};if(!x){var Ib=new MutationObserver(tb),Jb=function(a){Ib.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)Jb(document);else{var Oa=function(){Jb(document.body)};window.HTMLImports?window.HTMLImports.whenReady(Oa):requestAnimationFrame(function(){if("loading"===
document.readyState){var a=function(){Oa();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",a)}else Oa()})}Sa=function(){tb(Ib.takeRecords())}}var da={},xc=Promise.resolve(),Ha=null,vb=window.HTMLImports&&window.HTMLImports.whenReady||null,Ia,ka=null,W=null;C.prototype.ma=function(){!this.enqueued&&W&&(this.enqueued=!0,Ra(W))};C.prototype.b=function(a){a.__seenByShadyCSS||(a.__seenByShadyCSS=!0,this.customStyles.push(a),this.ma())};C.prototype.a=function(a){return a.__shadyCSSCachedStyle?
a.__shadyCSSCachedStyle:a.getStyle?a.getStyle():a};C.prototype.c=function(){for(var a=this.customStyles,b=0;b<a.length;b++){var c=a[b];if(!c.__shadyCSSCachedStyle){var d=this.a(c);d&&(d=d.__appliedElement||d,ka&&ka(d),c.__shadyCSSCachedStyle=d)}}return a};C.prototype.addCustomStyle=C.prototype.b;C.prototype.getStyleForCustomStyle=C.prototype.a;C.prototype.processStyles=C.prototype.c;Object.defineProperties(C.prototype,{transformCallback:{get:function(){return ka},set:function(a){ka=a}},validateCallback:{get:function(){return W},
set:function(a){var b=!1;W||(b=!0);W=a;b&&this.ma()}}});var Kb=new X;g.prototype.H=function(){Sa()};g.prototype.O=function(a){var b=this.s[a]=(this.s[a]||0)+1;return a+"-"+b};g.prototype.wa=function(a){return ba(a)};g.prototype.ya=function(a){return Q(a)};g.prototype.N=function(a){a=a.content.querySelectorAll("style");for(var b=[],c=0;c<a.length;c++){var d=a[c];b.push(d.textContent);d.parentNode.removeChild(d)}return b.join("").trim()};g.prototype.X=function(a){return(a=a.content.querySelector("style"))?
a.getAttribute("css-build")||"":""};g.prototype.prepareTemplate=function(a,b,c){if(!a.f){a.f=!0;a.name=b;a.extends=c;da[b]=a;var d=this.X(a),e=this.N(a);c={is:b,extends:c,Pa:d};x||v.a(a.content,b);this.c();var f=ia.test(e)||ha.test(e);ia.lastIndex=0;ha.lastIndex=0;e=Fa(e);f&&w&&this.a&&this.a.transformRules(e,b);a._styleAst=e;a.g=d;d=[];w||(d=H.N(a._styleAst));if(!d.length||w)b=this.W(c,a._styleAst,x?a.content:null,Na[b]),a.a=b;a.c=d}};g.prototype.W=function(a,b,c,d){b=v.b(a,b);if(b.length)return Ga(b,
a.is,c,d)};g.prototype.Z=function(a){var b=L(a),c=b.is;b=b.R;var d=Na[c];c=da[c];if(c){var e=c._styleAst;var f=c.c}return t.set(a,new t(e,d,f,0,b))};g.prototype.L=function(){!this.a&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(this.a=window.ShadyCSS.ApplyShim,this.a.invalidCallback=vc)};g.prototype.M=function(){var a=this;!this.b&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(this.b=window.ShadyCSS.CustomStyleInterface,this.b.transformCallback=function(b){a.w(b)},this.b.validateCallback=
function(){requestAnimationFrame(function(){(a.b.enqueued||a.i)&&a.f()})})};g.prototype.c=function(){this.L();this.M()};g.prototype.f=function(){this.c();if(this.b){var a=this.b.processStyles();this.b.enqueued&&(w?this.ua(a):(this.u(this.g,this.h),this.I(a)),this.b.enqueued=!1,this.i&&!w&&this.styleDocument())}};g.prototype.styleElement=function(a,b){var c=L(a).is,d=t.get(a);d||(d=this.Z(a));this.j(a)||(this.i=!0);b&&(d.K=d.K||{},Object.assign(d.K,b));if(w){if(d.K){b=d.K;for(var e in b)null===e?a.style.removeProperty(e):
a.style.setProperty(e,b[e])}if(((e=da[c])||this.j(a))&&e&&e.a&&!ub(e)){if(ub(e)||e._applyShimValidatingVersion!==e._applyShimNextVersion)this.c(),this.a&&this.a.transformRules(e._styleAst,c),e.a.textContent=v.b(a,d.D),wc(e);x&&(c=a.shadowRoot)&&(c.querySelector("style").textContent=v.b(a,d.D));d.D=e._styleAst}}else this.u(a,d),d.fa&&d.fa.length&&this.S(a,d)};g.prototype.l=function(a){return(a=a.getRootNode().host)?t.get(a)?a:this.l(a):this.g};g.prototype.j=function(a){return a===this.g};g.prototype.S=
function(a,b){var c=L(a).is,d=Kb.a(c,b.G,b.fa),e=d?d.styleElement:null,f=b.B;b.B=d&&d.B||this.O(c);e=H.w(a,b.G,b.B,e);x||H.u(a,b.B,f);d||Kb.c(c,b.G,e,b.B)};g.prototype.u=function(a,b){var c=this.l(a),d=t.get(c);c=Object.create(d.G||null);var e=H.O(a,b.D);a=H.W(d.D,a).C;Object.assign(c,e.Ha,a,e.La);this.Y(c,b.K);H.X(c);b.G=c};g.prototype.Y=function(a,b){for(var c in b){var d=b[c];if(d||0===d)a[c]=d}};g.prototype.styleDocument=function(a){this.styleSubtree(this.g,a)};g.prototype.styleSubtree=function(a,
b){var c=a.shadowRoot;(c||this.j(a))&&this.styleElement(a,b);if(b=c&&(c.children||c.childNodes))for(a=0;a<b.length;a++)this.styleSubtree(b[a]);else if(a=a.children||a.childNodes)for(b=0;b<a.length;b++)this.styleSubtree(a[b])};g.prototype.ua=function(a){for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);c&&this.ta(c)}};g.prototype.I=function(a){for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);c&&H.s(c,this.h.G)}};g.prototype.w=function(a){var b=this,c=ba(a);
R(c,function(a){x?v.w(a):v.N(a);w&&(b.c(),b.a&&b.a.transformRule(a))});w?a.textContent=Q(c):this.h.D.rules.push(c)};g.prototype.ta=function(a){if(w&&this.a){var b=ba(a);this.c();this.a.transformRules(b);a.textContent=Q(b)}};g.prototype.getComputedStyleValue=function(a,b){var c;w||(c=(t.get(a)||t.get(this.l(a))).G[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};g.prototype.xa=function(a,b){var c=a.getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=
a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===v.c){c=d[e+1];break}}}c&&b.push(v.c,c);w||(c=t.get(a))&&c.B&&b.push(H.g,c.B);ca(a,b.join(" "))};g.prototype.va=function(a){return t.get(a)};g.prototype.flush=g.prototype.H;g.prototype.prepareTemplate=g.prototype.prepareTemplate;g.prototype.styleElement=g.prototype.styleElement;g.prototype.styleDocument=g.prototype.styleDocument;g.prototype.styleSubtree=g.prototype.styleSubtree;g.prototype.getComputedStyleValue=g.prototype.getComputedStyleValue;
g.prototype.setElementClass=g.prototype.xa;g.prototype._styleInfoForNode=g.prototype.va;g.prototype.transformCustomStyleForDocument=g.prototype.w;g.prototype.getStyleAst=g.prototype.wa;g.prototype.styleAstToString=g.prototype.ya;g.prototype.flushCustomStyles=g.prototype.f;Object.defineProperties(g.prototype,{nativeShadow:{get:function(){return x}},nativeCss:{get:function(){return w}}});var E=new g;if(window.ShadyCSS){var Lb=window.ShadyCSS.ApplyShim;var Mb=window.ShadyCSS.CustomStyleInterface}window.ShadyCSS=
{ScopingShim:E,prepareTemplate:function(a,b,c){E.f();E.prepareTemplate(a,b,c)},styleSubtree:function(a,b){E.f();E.styleSubtree(a,b)},styleElement:function(a){E.f();E.styleElement(a)},styleDocument:function(a){E.f();E.styleDocument(a)},getComputedStyleValue:function(a,b){return E.getComputedStyleValue(a,b)},nativeCss:w,nativeShadow:x};Lb&&(window.ShadyCSS.ApplyShim=Lb);Mb&&(window.ShadyCSS.CustomStyleInterface=Mb);var Pa=window.customElements,la=window.HTMLImports;window.WebComponents=window.WebComponents||
{};if(Pa&&Pa.polyfillWrapFlushCallback){var ma,Nb=function(){if(ma){var a=ma;ma=null;a();return!0}},Ob=la.whenReady;Pa.polyfillWrapFlushCallback(function(a){ma=a;Ob(Nb)});la.whenReady=function(a){Ob(function(){Nb()?la.whenReady(a):a()})}}la.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})});var Pb=document.createElement("style");Pb.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";
var Qb=document.querySelector("head");Qb.insertBefore(Pb,Qb.firstChild)})();}).call(this);

//# sourceMappingURL=webcomponents-lite.js.map
