(function(){/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var Oa="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
(function(){function g(){var a=this;this.s={};this.g=document.documentElement;var b=new ma;b.rules=[];this.h=q.set(this.g,new q(b));this.i=!1;this.b=this.a=null;Pa(function(){a.c()})}function A(){this.customStyles=[];this.enqueued=!1}function Qa(){}function W(a){this.cache={};this.f=void 0===a?100:a}function l(){}function q(a,b,c,d,e){this.D=a||null;this.b=b||null;this.da=c||[];this.K=null;this.R=e||"";this.a=this.B=this.G=null}function p(){}function ma(){this.end=this.start=0;this.rules=this.parent=
this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}function Qb(a){function b(b,c){Object.defineProperty(b,"innerHTML",{enumerable:c.enumerable,configurable:!0,get:c.get,set:function(b){var e=this,d=void 0;k(this)&&(d=[],H(this,function(a){a!==e&&d.push(a)}));c.set.call(this,b);if(d)for(var f=0;f<d.length;f++){var h=d[f];1===h.__CE_state&&a.disconnectedCallback(h)}this.ownerDocument.__CE_hasRegistry?a.f(this):a.l(this);
return b}})}function c(b,c){w(b,"insertAdjacentElement",function(b,e){var d=k(e);b=c.call(this,b,e);d&&a.a(e);k(b)&&a.b(e);return b})}Ra?w(Element.prototype,"attachShadow",function(a){return this.__CE_shadowRoot=a=Ra.call(this,a)}):console.warn("Custom Elements: `Element#attachShadow` was not patched.");if(na&&na.get)b(Element.prototype,na);else if(oa&&oa.get)b(HTMLElement.prototype,oa);else{var d=pa.call(document,"div");a.w(function(a){b(a,{enumerable:!0,configurable:!0,get:function(){return Sa.call(this,
!0).innerHTML},set:function(a){var b="template"===this.localName?this.content:this;for(d.innerHTML=a;0<b.childNodes.length;)qa.call(b,b.childNodes[0]);for(;0<d.childNodes.length;)X.call(b,d.childNodes[0])}})})}w(Element.prototype,"setAttribute",function(b,c){if(1!==this.__CE_state)return Ta.call(this,b,c);var d=ra.call(this,b);Ta.call(this,b,c);c=ra.call(this,b);a.attributeChangedCallback(this,b,d,c,null)});w(Element.prototype,"setAttributeNS",function(b,c,d){if(1!==this.__CE_state)return Ua.call(this,
b,c,d);var e=Y.call(this,b,c);Ua.call(this,b,c,d);d=Y.call(this,b,c);a.attributeChangedCallback(this,c,e,d,b)});w(Element.prototype,"removeAttribute",function(b){if(1!==this.__CE_state)return Va.call(this,b);var c=ra.call(this,b);Va.call(this,b);null!==c&&a.attributeChangedCallback(this,b,c,null,null)});w(Element.prototype,"removeAttributeNS",function(b,c){if(1!==this.__CE_state)return Wa.call(this,b,c);var d=Y.call(this,b,c);Wa.call(this,b,c);var e=Y.call(this,b,c);d!==e&&a.attributeChangedCallback(this,
c,d,e,b)});Xa?c(HTMLElement.prototype,Xa):Ya?c(Element.prototype,Ya):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");Za(a,Element.prototype,{oa:Sb,append:Tb});Ub(a,{Da:Vb,Ca:Wb,replaceWith:Xb,remove:Yb})}function Ub(a,b){var c=Element.prototype;c.before=function(c){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof Node&&k(a)});b.Da.apply(this,d);for(var h=0;h<f.length;h++)a.a(f[h]);if(k(this))for(f=0;f<d.length;f++)h=
d[f],h instanceof Element&&a.b(h)};c.after=function(c){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof Node&&k(a)});b.Ca.apply(this,d);for(var h=0;h<f.length;h++)a.a(f[h]);if(k(this))for(f=0;f<d.length;f++)h=d[f],h instanceof Element&&a.b(h)};c.replaceWith=function(c){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof Node&&k(a)});var h=k(this);b.replaceWith.apply(this,d);for(var m=0;m<f.length;m++)a.a(f[m]);
if(h)for(a.a(this),f=0;f<d.length;f++)h=d[f],h instanceof Element&&a.b(h)};c.remove=function(){var c=k(this);b.remove.call(this);c&&a.a(this)}}function Zb(a){function b(b,d){Object.defineProperty(b,"textContent",{enumerable:d.enumerable,configurable:!0,get:d.get,set:function(b){if(this.nodeType===Node.TEXT_NODE)d.set.call(this,b);else{var c=void 0;if(this.firstChild){var e=this.childNodes,m=e.length;if(0<m&&k(this)){c=Array(m);for(var D=0;D<m;D++)c[D]=e[D]}}d.set.call(this,b);if(c)for(b=0;b<c.length;b++)a.a(c[b])}}})}
w(Node.prototype,"insertBefore",function(b,d){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=$a.call(this,b,d);if(k(this))for(d=0;d<c.length;d++)a.b(c[d]);return b}c=k(b);d=$a.call(this,b,d);c&&a.a(b);k(this)&&a.b(b);return d});w(Node.prototype,"appendChild",function(b){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=X.call(this,b);if(k(this))for(var e=0;e<c.length;e++)a.b(c[e]);return b}c=k(b);e=X.call(this,b);c&&a.a(b);k(this)&&
a.b(b);return e});w(Node.prototype,"cloneNode",function(b){b=Sa.call(this,b);this.ownerDocument.__CE_hasRegistry?a.f(b):a.l(b);return b});w(Node.prototype,"removeChild",function(b){var c=k(b),e=qa.call(this,b);c&&a.a(b);return e});w(Node.prototype,"replaceChild",function(b,d){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=ab.call(this,b,d);if(k(this))for(a.a(d),d=0;d<c.length;d++)a.b(c[d]);return b}c=k(b);var f=ab.call(this,b,d),h=k(this);h&&a.a(d);c&&a.a(b);h&&
a.b(b);return f});sa&&sa.get?b(Node.prototype,sa):a.w(function(a){b(a,{enumerable:!0,configurable:!0,get:function(){for(var a=[],b=0;b<this.childNodes.length;b++)a.push(this.childNodes[b].textContent);return a.join("")},set:function(a){for(;this.firstChild;)qa.call(this,this.firstChild);X.call(this,document.createTextNode(a))}})})}function $b(a){w(Document.prototype,"createElement",function(b){if(this.__CE_hasRegistry){var c=a.c(b);if(c)return new c.constructor}b=pa.call(this,b);a.g(b);return b});
w(Document.prototype,"importNode",function(b,c){b=ac.call(this,b,c);this.__CE_hasRegistry?a.f(b):a.l(b);return b});w(Document.prototype,"createElementNS",function(b,c){if(this.__CE_hasRegistry&&(null===b||"http://www.w3.org/1999/xhtml"===b)){var d=a.c(c);if(d)return new d.constructor}b=bc.call(this,b,c);a.g(b);return b});Za(a,Document.prototype,{oa:cc,append:dc})}function Za(a,b,c){b.prepend=function(b){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof
Node&&k(a)});c.oa.apply(this,d);for(var h=0;h<f.length;h++)a.a(f[h]);if(k(this))for(f=0;f<d.length;f++)h=d[f],h instanceof Element&&a.b(h)};b.append=function(b){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof Node&&k(a)});c.append.apply(this,d);for(var h=0;h<f.length;h++)a.a(f[h]);if(k(this))for(f=0;f<d.length;f++)h=d[f],h instanceof Element&&a.b(h)}}function ec(a){window.HTMLElement=function(){function b(){var b=this.constructor,d=a.H(b);if(!d)throw Error("The custom element being constructed was not registered with `customElements`.");
var e=d.constructionStack;if(0===e.length)return e=pa.call(document,d.localName),Object.setPrototypeOf(e,b.prototype),e.__CE_state=1,e.__CE_definition=d,a.g(e),e;d=e.length-1;var f=e[d];if(f===bb)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");e[d]=bb;Object.setPrototypeOf(f,b.prototype);a.g(f);return f}b.prototype=fc.prototype;return b}()}function x(a){this.c=!1;this.a=a;this.h=new Map;this.f=function(a){return a()};this.b=!1;
this.g=[];this.i=new ta(a,document)}function cb(){var a=this;this.b=this.a=void 0;this.c=new Promise(function(b){a.b=b;a.a&&b(a.a)})}function ta(a,b){this.c=a;this.a=b;this.b=void 0;this.c.f(this.a);"loading"===this.a.readyState&&(this.b=new MutationObserver(this.g.bind(this)),this.b.observe(this.a,{childList:!0,subtree:!0}))}function v(){this.u=new Map;this.s=new Map;this.j=[];this.h=!1}function I(a,b){L[M]=a;L[M+1]=b;M+=2;2===M&&(ua?ua(N):gc())}function hc(){return function(){return process.Wa(N)}}
function ic(){return"undefined"!==typeof va?function(){va(N)}:wa()}function jc(){var a=0,b=new db(N),c=document.createTextNode("");b.observe(c,{characterData:!0});return function(){c.data=a=++a%2}}function kc(){var a=new MessageChannel;a.port1.onmessage=N;return function(){return a.port2.postMessage(0)}}function wa(){var a=setTimeout;return function(){return a(N,1)}}function N(){for(var a=0;a<M;a+=2)(0,L[a])(L[a+1]),L[a]=void 0,L[a+1]=void 0;M=0}function lc(){try{var a=require("vertx");va=a.Ya||a.Xa;
return ic()}catch(b){return wa()}}function xa(a,b){var c=this,d=new this.constructor(O);void 0===d[Z]&&eb(d);var e=c.o;if(e){var f=arguments[e-1];I(function(){return fb(e,d,f,c.m)})}else ya(c,d,a,b);return d}function za(a){if(a&&"object"===typeof a&&a.constructor===this)return a;var b=new this(O);R(b,a);return b}function O(){}function gb(a){try{return a.then}catch(b){return S.error=b,S}}function mc(a,b,c,d){try{a.call(b,c,d)}catch(e){return e}}function nc(a,b,c){I(function(a){var d=!1,f=mc(c,b,function(c){d||
(d=!0,b!==c?R(a,c):E(a,c))},function(b){d||(d=!0,y(a,b))});!d&&f&&(d=!0,y(a,f))},a)}function oc(a,b){1===b.o?E(a,b.m):2===b.o?y(a,b.m):ya(b,void 0,function(b){return R(a,b)},function(b){return y(a,b)})}function hb(a,b,c){b.constructor===a.constructor&&c===xa&&b.constructor.resolve===za?oc(a,b):c===S?(y(a,S.error),S.error=null):void 0===c?E(a,b):"function"===typeof c?nc(a,b,c):E(a,b)}function R(a,b){if(a===b)y(a,new TypeError("You cannot resolve a promise with itself"));else{var c=typeof b;null===
b||"object"!==c&&"function"!==c?E(a,b):hb(a,b,gb(b))}}function pc(a){a.ia&&a.ia(a.m);Aa(a)}function E(a,b){void 0===a.o&&(a.m=b,a.o=1,0!==a.P.length&&I(Aa,a))}function y(a,b){void 0===a.o&&(a.o=2,a.m=b,I(pc,a))}function ya(a,b,c,d){var e=a.P,f=e.length;a.ia=null;e[f]=b;e[f+1]=c;e[f+2]=d;0===f&&a.o&&I(Aa,a)}function Aa(a){var b=a.P,c=a.o;if(0!==b.length){for(var d,e,f=a.m,h=0;h<b.length;h+=3)d=b[h],e=b[h+c],d?fb(c,d,e,f):e(f);a.P.length=0}}function ib(){this.error=null}function fb(a,b,c,d){var e="function"===
typeof c;if(e){try{var f=c(d)}catch(Rb){Ba.error=Rb,f=Ba}if(f===Ba){var h=!0;var m=f.error;f.error=null}else var D=!0;if(b===f){y(b,new TypeError("A promises callback cannot return that same promise."));return}}else f=d,D=!0;void 0===b.o&&(e&&D?R(b,f):h?y(b,m):1===a?E(b,f):2===a&&y(b,f))}function qc(a,b){try{b(function(b){R(a,b)},function(b){y(a,b)})}catch(c){y(a,c)}}function eb(a){a[Z]=jb++;a.o=void 0;a.m=void 0;a.P=[]}function T(a,b){this.Ba=a;this.F=new a(O);this.F[Z]||eb(this.F);kb(b)?(this.T=
this.length=b.length,this.m=Array(this.length),0===this.length?E(this.F,this.m):(this.length=this.length||0,this.Aa(b),0===this.T&&E(this.F,this.m))):y(this.F,Error("Array Methods must be provided an Array"))}function t(a){this[Z]=jb++;this.m=this.o=void 0;this.P=[];if(O!==a){if("function"!==typeof a)throw new TypeError("You must pass a resolver function as the first argument to the promise constructor");if(this instanceof t)qc(this,a);else throw new TypeError("Failed to construct 'Promise': Please use the 'new' operator, this object constructor cannot be called as a function.");
}}function lb(a){var b=rc.has(a);a=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(a);return!b&&a}function k(a){var b=a.isConnected;if(void 0!==b)return b;for(;a&&!(a.__CE_isImportDocument||a instanceof Document);)a=a.parentNode||(window.ShadowRoot&&a instanceof ShadowRoot?a.host:void 0);return!(!a||!(a.__CE_isImportDocument||a instanceof Document))}function Ca(a,b){for(;b&&b!==a&&!b.nextSibling;)b=b.parentNode;return b&&b!==a?b.nextSibling:null}function H(a,b,c){c=c?c:new Set;for(var d=a;d;){if(d.nodeType===
Node.ELEMENT_NODE){var e=d;b(e);var f=e.localName;if("link"===f&&"import"===e.getAttribute("rel")){d=e.import;if(d instanceof Node&&!c.has(d))for(c.add(d),d=d.firstChild;d;d=d.nextSibling)H(d,b,c);d=Ca(a,e);continue}else if("template"===f){d=Ca(a,e);continue}if(e=e.__CE_shadowRoot)for(e=e.firstChild;e;e=e.nextSibling)H(e,b,c)}d=d.firstChild?d.firstChild:Ca(a,d)}}function w(a,b,c){a[b]=c}function Da(a){a=a.replace(B.Fa,"").replace(B.port,"");var b=mb,c=a,d=new ma;d.start=0;d.end=c.length;for(var e=
d,f=0,h=c.length;f<h;f++)if("{"===c[f]){e.rules||(e.rules=[]);var m=e,D=m.rules[m.rules.length-1]||null;e=new ma;e.start=f+1;e.parent=m;e.previous=D;m.rules.push(e)}else"}"===c[f]&&(e.end=f+1,e=e.parent||d);return b(d,a)}function mb(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=sc(c),c=c.replace(B.na," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===
c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=F.MEDIA_RULE:c.match(B.Ja)&&(a.type=F.Z,a.keyframesName=a.selector.split(B.na).pop()):a.type=0===c.indexOf("--")?F.fa:F.STYLE_RULE);if(c=a.rules)for(var d=0,e=c.length,f;d<e&&(f=c[d]);d++)mb(f,b);return a}function sc(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(a,c){a=c;for(c=6-a.length;c--;)a="0"+a;return"\\"+a})}function nb(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===
f.selector.indexOf("--"));if(f){f=0;for(var h=e.length,m;f<h&&(m=e[f]);f++)d=nb(m,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(B.ja,"").replace(B.ma,""),b=b.replace(B.Ka,"").replace(B.Na,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}function ob(a){n=a&&a.shimcssproperties?!1:u||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}function P(a,b){if(!a)return"";
"string"===typeof a&&(a=Da(a));b&&Q(a,b);return nb(a,n)}function aa(a){!a.__cssRules&&a.textContent&&(a.__cssRules=Da(a.textContent));return a.__cssRules||null}function pb(a){return!!a.parent&&a.parent.type===F.Z}function Q(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===F.MEDIA_RULE){var h=a.selector.match(tc);h&&(window.matchMedia(h[1]).matches||(e=!0))}f===F.STYLE_RULE?b(a):c&&f===F.Z?c(a):f===F.fa&&(e=!0);if((a=a.rules)&&!e){e=0;f=a.length;for(var m;e<f&&(m=a[e]);e++)Q(m,b,c,d)}}}function Ea(a,b,c,
d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;qb(e,c,d);return e}function qb(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);J?a.compareDocumentPosition(J)===Node.DOCUMENT_POSITION_PRECEDING&&(J=a):J=a}function rb(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");a:{var d=0;var e=c+3;for(var f=a.length;e<f;e++)if("("===a[e])d++;else if(")"===a[e]&&0===--d)break a;e=-1}d=a.substring(c+4,e);c=a.substring(0,c);a=rb(a.substring(e+
1),b);e=d.indexOf(",");return-1===e?b(c,d.trim(),"",a):b(c,d.substring(0,e).trim(),d.substring(e+1).trim(),a)}function ba(a,b){u?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}function K(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,R:c}}function sb(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=
c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode();var h=e;var m=[];h.classList?m=Array.from(h.classList):h instanceof window.SVGElement&&h.hasAttribute("class")&&(m=h.getAttribute("class").split(/\s+/));h=m;m=h.indexOf(r.c);(h=-1<m?h[m+1]:"")&&f===e.ownerDocument?r.a(e,h,!0):f.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(f=f.host)&&(f=K(f).is,h!==f&&(h&&r.a(e,h,!0),r.a(e,f)))}}}}function uc(a){if(a=ca[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=
a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function tb(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function vc(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a.b||(a.b=!0,wc.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a.b=!1}))}function Pa(a){requestAnimationFrame(function(){ub?ub(a):(Fa||(Fa=new Promise(function(a){Ga=a}),"complete"===document.readyState?Ga():document.addEventListener("readystatechange",
function(){"complete"===document.readyState&&Ga()})),Fa.then(function(){a&&a()}))})}(function(){if(!function(){var a=document.createEvent("Event");a.initEvent("foo",!0,!0);a.preventDefault();return a.defaultPrevented}()){var a=Event.prototype.preventDefault;Event.prototype.preventDefault=function(){this.cancelable&&(a.call(this),Object.defineProperty(this,"defaultPrevented",{get:function(){return!0},configurable:!0}))}}var b=/Trident/.test(navigator.userAgent);if(!window.CustomEvent||b&&"function"!==
typeof window.CustomEvent)window.CustomEvent=function(a,b){b=b||{};var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c},window.CustomEvent.prototype=window.Event.prototype;if(!window.Event||b&&"function"!==typeof window.Event){var c=window.Event;window.Event=function(a,b){b=b||{};var c=document.createEvent("Event");c.initEvent(a,!!b.bubbles,!!b.cancelable);return c};if(c)for(var d in c)window.Event[d]=c[d];window.Event.prototype=c.prototype}if(!window.MouseEvent||
b&&"function"!==typeof window.MouseEvent){b=window.MouseEvent;window.MouseEvent=function(a,b){b=b||{};var c=document.createEvent("MouseEvent");c.initMouseEvent(a,!!b.bubbles,!!b.cancelable,b.view||window,b.detail,b.screenX,b.screenY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget);return c};if(b)for(d in b)window.MouseEvent[d]=b[d];window.MouseEvent.prototype=b.prototype}Array.from||(Array.from=function(a){return[].slice.call(a)});Object.assign||(Object.assign=
function(a,b){for(var c=[].slice.call(arguments,1),d=0,e;d<c.length;d++)if(e=c[d])for(var f=a,g=e,k=Object.getOwnPropertyNames(g),l=0;l<k.length;l++)e=k[l],f[e]=g[e];return a})})(window.WebComponents);(function(){function a(){}var b="undefined"===typeof HTMLTemplateElement;/Trident/.test(navigator.userAgent)&&function(){var a=Document.prototype.importNode;Document.prototype.importNode=function(){var b=a.apply(this,arguments);if(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE){var c=this.createDocumentFragment();
c.appendChild(b);return c}return b}}();var c=Node.prototype.cloneNode,d=Document.prototype.createElement,e=Document.prototype.importNode,f=function(){if(!b){var a=document.createElement("template"),c=document.createElement("template");c.content.appendChild(document.createElement("div"));a.content.appendChild(c);a=a.cloneNode(!0);return 0===a.content.childNodes.length||0===a.content.firstChild.content.childNodes.length||!(document.createDocumentFragment().cloneNode()instanceof DocumentFragment)}}();
if(b){var h=function(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case "\u00a0":return"&nbsp;"}},m=function(b){Object.defineProperty(b,"innerHTML",{get:function(){for(var a="",b=this.content.firstChild;b;b=b.nextSibling)a+=b.outerHTML||b.data.replace(r,h);return a},set:function(b){g.body.innerHTML=b;for(a.b(g);this.content.firstChild;)this.content.removeChild(this.content.firstChild);for(;g.body.firstChild;)this.content.appendChild(g.body.firstChild)},configurable:!0})},
g=document.implementation.createHTMLDocument("template"),k=!0,l=document.createElement("style");l.textContent="template{display:none;}";var p=document.head;p.insertBefore(l,p.firstElementChild);a.prototype=Object.create(HTMLElement.prototype);var q=!document.createElement("div").hasOwnProperty("innerHTML");a.J=function(b){if(!b.content){b.content=g.createDocumentFragment();for(var c;c=b.firstChild;)b.content.appendChild(c);if(q)b.__proto__=a.prototype;else if(b.cloneNode=function(b){return a.a(this,
b)},k)try{m(b)}catch(Pc){k=!1}a.b(b.content)}};m(a.prototype);a.b=function(b){b=b.querySelectorAll("template");for(var c=0,d=b.length,e;c<d&&(e=b[c]);c++)a.J(e)};document.addEventListener("DOMContentLoaded",function(){a.b(document)});Document.prototype.createElement=function(){var b=d.apply(this,arguments);"template"===b.localName&&a.J(b);return b};var r=/[&\u00A0<>]/g}if(b||f)a.a=function(a,b){var d=c.call(a,!1);this.J&&this.J(d);b&&(d.content.appendChild(c.call(a.content,!0)),this.ca(d.content,
a.content));return d},a.prototype.cloneNode=function(b){return a.a(this,b)},a.ca=function(a,b){if(b.querySelectorAll){b=b.querySelectorAll("template");a=a.querySelectorAll("template");for(var c=0,d=a.length,e,f;c<d;c++)f=b[c],e=a[c],this.J&&this.J(f),e.parentNode.replaceChild(f.cloneNode(!0),e)}},Node.prototype.cloneNode=function(b){if(this instanceof DocumentFragment)if(b)var d=this.ownerDocument.importNode(this,!0);else return this.ownerDocument.createDocumentFragment();else d=c.call(this,b);b&&
a.ca(d,this);return d},Document.prototype.importNode=function(b,c){if("template"===b.localName)return a.a(b,c);var d=e.call(this,b,c);c&&a.ca(d,b);return d},f&&(window.HTMLTemplateElement.prototype.cloneNode=function(b){return a.a(this,b)});b&&(window.HTMLTemplateElement=a)})();var Ha;Array.isArray?Ha=Array.isArray:Ha=function(a){return"[object Array]"===Object.prototype.toString.call(a)};var kb=Ha,M=0,va,ua,vb="undefined"!==typeof window?window:void 0,wb=vb||{},db=wb.MutationObserver||wb.WebKitMutationObserver,
xc="undefined"!==typeof Uint8ClampedArray&&"undefined"!==typeof importScripts&&"undefined"!==typeof MessageChannel,L=Array(1E3);var gc="undefined"===typeof self&&"undefined"!==typeof process&&"[object process]"==={}.toString.call(process)?hc():db?jc():xc?kc():vb||"function"!==typeof require?wa():lc();var Z=Math.random().toString(36).substring(16),S=new ib,Ba=new ib,jb=0;T.prototype.Aa=function(a){for(var b=0;void 0===this.o&&b<a.length;b++)this.za(a[b],b)};T.prototype.za=function(a,b){var c=this.Ba,
d=c.resolve;d===za?(d=gb(a),d===xa&&void 0!==a.o?this.aa(a.o,b,a.m):"function"!==typeof d?(this.T--,this.m[b]=a):c===t?(c=new c(O),hb(c,a,d),this.ba(c,b)):this.ba(new c(function(b){return b(a)}),b)):this.ba(d(a),b)};T.prototype.aa=function(a,b,c){var d=this.F;void 0===d.o&&(this.T--,2===a?y(d,c):this.m[b]=c);0===this.T&&E(d,this.m)};T.prototype.ba=function(a,b){var c=this;ya(a,void 0,function(a){return c.aa(1,b,a)},function(a){return c.aa(2,b,a)})};t.all=function(a){return(new T(this,a)).F};t.race=
function(a){var b=this;return kb(a)?new b(function(c,d){for(var e=a.length,f=0;f<e;f++)b.resolve(a[f]).then(c,d)}):new b(function(a,b){return b(new TypeError("You must pass an array to race."))})};t.resolve=za;t.reject=function(a){var b=new this(O);y(b,a);return b};t.Ua=function(a){ua=a};t.Ta=function(a){I=a};t.Qa=I;t.prototype={constructor:t,then:xa,a:function(a){return this.then(null,a)}};window.Promise||(window.Promise=t,t.prototype["catch"]=t.prototype.a);(function(a){function b(a,b){if("function"===
typeof window.CustomEvent)return new CustomEvent(a,b);var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c}function c(a){if(l)return a.ownerDocument!==document?a.ownerDocument:null;var b=a.__importDoc;if(!b&&a.parentNode){b=a.parentNode;if("function"===typeof b.closest)b=b.closest("link[rel=import]");else for(;!m(b)&&(b=b.parentNode););a.__importDoc=b}return b}function d(a){var b=document.querySelectorAll("link[rel=import]:not(import-dependency)"),
c=b.length;c?k(b,function(b){return h(b,function(){0===--c&&a()})}):a()}function e(a){function b(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",b),a())}document.addEventListener("readystatechange",b);b()}function f(a){e(function(){return d(function(){return a&&a()})})}function h(a,b){if(a.__loaded)b&&b();else if("script"===a.localName&&!a.src||"style"===a.localName&&!a.firstChild)a.__loaded=!0,b&&b();else{var c=function(d){a.removeEventListener(d.type,
c);a.__loaded=!0;b&&b()};a.addEventListener("load",c);v&&"style"===a.localName||a.addEventListener("error",c)}}function m(a){return a.nodeType===Node.ELEMENT_NODE&&"link"===a.localName&&"import"===a.rel}function g(){var a=this;this.a={};this.b=0;this.f=new MutationObserver(function(b){return a.l(b)});this.f.observe(document.head,{childList:!0,subtree:!0});this.c(document)}function k(a,b,c){var d=a?a.length:0,e=c?-1:1;for(c=c?d-1:0;c<d&&0<=c;c+=e)b(a[c],c)}var l="import"in document.createElement("link"),
p=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",{get:function(){return p||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var q=/(^\/)|(^#)|(^[\w-\d]*:)/,r=/(url\()([^)]*)(\))/g,u=/(@import[\s]+(?!url\())([^;]*)(;)/g,x=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,n={Ga:function(a,b){a.href&&a.setAttribute("href",n.ea(a.getAttribute("href"),b));a.src&&a.setAttribute("src",n.ea(a.getAttribute("src"),b));
if("style"===a.localName){var c=n.pa(a.textContent,b,r);a.textContent=n.pa(c,b,u)}},pa:function(a,b,c){return a.replace(c,function(a,c,d,e){a=d.replace(/["']/g,"");b&&(a=n.qa(a,b));return c+"'"+a+"'"+e})},ea:function(a,b){return a&&q.test(a)?a:n.qa(a,b)},qa:function(a,b){if(void 0===n.$){n.$=!1;try{var c=new URL("b","http://a");c.pathname="c%20d";n.$="http://a/c%20d"===c.href}catch(Qc){}}if(n.$)return(new URL(a,b)).href;c=n.ya;c||(c=document.implementation.createHTMLDocument("temp"),n.ya=c,c.ha=c.createElement("base"),
c.head.appendChild(c.ha),c.ga=c.createElement("a"));c.ha.href=b;c.ga.href=a;return c.ga.href||a}},w={async:!0,load:function(a,b,c){if(a)if(a.match(/^data:/)){a=a.split(",");var d=a[1];d=-1<a[0].indexOf(";base64")?atob(d):decodeURIComponent(d);b(d)}else{var e=new XMLHttpRequest;e.open("GET",a,w.async);e.onload=function(){var a=e.responseURL||e.getResponseHeader("Location");a&&0===a.indexOf("/")&&(a=(location.origin||location.protocol+"//"+location.host)+a);var d=e.response||e.responseText;304===e.status||
0===e.status||200<=e.status&&300>e.status?b(d,a):c(d)};e.send()}else c("error: href must be specified")}},v=/Trident/.test(navigator.userAgent)||/Edge\/\d./i.test(navigator.userAgent);g.prototype.c=function(a){var b=this;k(a.querySelectorAll("link[rel=import]"),function(a){return b.h(a)})};g.prototype.h=function(a){var b=this,c=a.href;if(void 0!==this.a[c]){var d=this.a[c];d&&d.__loaded&&(a.import=d,this.g(a))}else this.b++,this.a[c]="pending",w.load(c,function(a,d){a=b.s(a,d||c);b.a[c]=a;b.b--;b.c(a);
b.i()},function(){b.a[c]=null;b.b--;b.i()})};g.prototype.s=function(a,b){if(!a)return document.createDocumentFragment();v&&(a=a.replace(x,function(a,b,c){return-1===a.indexOf("type=")?b+" type=import-disable "+c:a}));var c=document.createElement("template");c.innerHTML=a;if(c.content)a=c.content;else for(a=document.createDocumentFragment();c.firstChild;)a.appendChild(c.firstChild);if(c=a.querySelector("base"))b=n.ea(c.getAttribute("href"),b),c.removeAttribute("href");var d=0;k(a.querySelectorAll('link[rel=import], link[rel=stylesheet][href][type=import-disable],\n    style:not([type]), link[rel=stylesheet][href]:not([type]),\n    script:not([type]), script[type="application/javascript"],\n    script[type="text/javascript"]'),
function(a){h(a);n.Ga(a,b);a.setAttribute("import-dependency","");"script"===a.localName&&!a.src&&a.textContent&&(a.setAttribute("src","data:text/javascript;charset=utf-8,"+encodeURIComponent(a.textContent+("\n//# sourceURL="+b+(d?"-"+d:"")+".js\n"))),a.textContent="",d++)});return a};g.prototype.i=function(){var a=this;if(!this.b){this.f.disconnect();this.flatten(document);var b=!1,c=!1,d=function(){c&&b&&(a.c(document),a.b||(a.f.observe(document.head,{childList:!0,subtree:!0}),a.j()))};this.w(function(){c=
!0;d()});this.u(function(){b=!0;d()})}};g.prototype.flatten=function(a){var b=this;k(a.querySelectorAll("link[rel=import]"),function(a){var c=b.a[a.href];(a.import=c)&&c.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(b.a[a.href]=a,a.readyState="loading",a.import=a,b.flatten(c),a.appendChild(c))})};g.prototype.u=function(a){function b(e){if(e<d){var f=c[e],g=document.createElement("script");f.removeAttribute("import-dependency");k(f.attributes,function(a){return g.setAttribute(a.name,a.value)});p=g;f.parentNode.replaceChild(g,
f);h(g,function(){p=null;b(e+1)})}else a()}var c=document.querySelectorAll("script[import-dependency]"),d=c.length;b(0)};g.prototype.w=function(a){var b=document.querySelectorAll("style[import-dependency],\n    link[rel=stylesheet][import-dependency]"),d=b.length;if(d){var e=v&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");k(b,function(b){h(b,function(){b.removeAttribute("import-dependency");0===--d&&a()});if(e&&b.parentNode!==document.head){var f=document.createElement(b.localName);
f.__appliedElement=b;f.setAttribute("type","import-placeholder");b.parentNode.insertBefore(f,b.nextSibling);for(f=c(b);f&&c(f);)f=c(f);f.parentNode!==document.head&&(f=null);document.head.insertBefore(b,f);b.removeAttribute("type")}})}else a()};g.prototype.j=function(){var a=this;k(document.querySelectorAll("link[rel=import]"),function(b){return a.g(b)},!0)};g.prototype.g=function(a){a.__loaded||(a.__loaded=!0,a.import&&(a.import.readyState="complete"),a.dispatchEvent(b(a.import?"load":"error",{bubbles:!1,
cancelable:!1,detail:void 0})))};g.prototype.l=function(a){var b=this;k(a,function(a){return k(a.addedNodes,function(a){a&&a.nodeType===Node.ELEMENT_NODE&&(m(a)?b.h(a):b.c(a))})})};if(l){k(document.querySelectorAll("link[rel=import]"),function(a){a.import&&"loading"===a.import.readyState||(a.__loaded=!0)});var y=function(a){a=a.target;m(a)&&(a.__loaded=!0)};document.addEventListener("load",y,!0);document.addEventListener("error",y,!0)}else{var t=Object.getOwnPropertyDescriptor(Node.prototype,"baseURI");
Object.defineProperty((!t||t.configurable?Node:Element).prototype,"baseURI",{get:function(){var a=m(this)?this:c(this);return a?a.href:t&&t.get?t.get.call(this):(document.querySelector("base")||window.location).href},configurable:!0,enumerable:!0});e(function(){return new g})}f(function(){return document.dispatchEvent(b("HTMLImportsLoaded",{cancelable:!0,bubbles:!0,detail:void 0}))});a.useNative=l;a.whenReady=f;a.importForElement=c})(window.HTMLImports=window.HTMLImports||{});window.WebComponents=
window.WebComponents||{flags:{}};var xb=document.querySelector('script[src*="webcomponents-lite.js"]'),yc=/wc-(.+)/,z={};if(!z.noOpts){location.search.slice(1).split("&").forEach(function(a){a=a.split("=");var b;a[0]&&(b=a[0].match(yc))&&(z[b[1]]=a[1]||!0)});if(xb)for(var yb=0,da;da=xb.attributes[yb];yb++)"src"!==da.name&&(z[da.name]=da.value||!0);if(z.log&&z.log.split){var zc=z.log.split(",");z.log={};zc.forEach(function(a){z.log[a]=!0})}else z.log={}}window.WebComponents.flags=z;var zb=z.shadydom;
zb&&(window.ShadyDOM=window.ShadyDOM||{},window.ShadyDOM.force=zb);var Ab=z.register||z.ce;Ab&&window.customElements&&(window.customElements.forcePolyfill=Ab);var rc=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));v.prototype.I=function(a,b){this.u.set(a,b);this.s.set(b.constructor,b)};v.prototype.c=function(a){return this.u.get(a)};v.prototype.H=function(a){return this.s.get(a)};v.prototype.w=function(a){this.h=
!0;this.j.push(a)};v.prototype.l=function(a){var b=this;this.h&&H(a,function(a){return b.g(a)})};v.prototype.g=function(a){if(this.h&&!a.__CE_patched){a.__CE_patched=!0;for(var b=0;b<this.j.length;b++)this.j[b](a)}};v.prototype.b=function(a){var b=[];H(a,function(a){return b.push(a)});for(a=0;a<b.length;a++){var c=b[a];1===c.__CE_state?this.connectedCallback(c):this.i(c)}};v.prototype.a=function(a){var b=[];H(a,function(a){return b.push(a)});for(a=0;a<b.length;a++){var c=b[a];1===c.__CE_state&&this.disconnectedCallback(c)}};
v.prototype.f=function(a,b){var c=this;b=b?b:{};var d=b.Oa||new Set,e=b.ra||function(a){return c.i(a)},f=[];H(a,function(a){if("link"===a.localName&&"import"===a.getAttribute("rel")){var b=a.import;b instanceof Node&&"complete"===b.readyState?(b.__CE_isImportDocument=!0,b.__CE_hasRegistry=!0):a.addEventListener("load",function(){var b=a.import;b.__CE_documentLoadHandled||(b.__CE_documentLoadHandled=!0,b.__CE_isImportDocument=!0,b.__CE_hasRegistry=!0,d.delete(b),c.f(b,{Oa:d,ra:e}))})}else f.push(a)},
d);if(this.h)for(a=0;a<f.length;a++)this.g(f[a]);for(a=0;a<f.length;a++)e(f[a])};v.prototype.i=function(a){if(void 0===a.__CE_state){var b=this.c(a.localName);if(b){b.constructionStack.push(a);var c=b.constructor;try{try{if(new c!==a)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{b.constructionStack.pop()}}catch(f){throw a.__CE_state=2,f;}a.__CE_state=1;a.__CE_definition=b;if(b.attributeChangedCallback)for(b=b.observedAttributes,c=0;c<b.length;c++){var d=
b[c],e=a.getAttribute(d);null!==e&&this.attributeChangedCallback(a,d,null,e,null)}k(a)&&this.connectedCallback(a)}}};v.prototype.connectedCallback=function(a){var b=a.__CE_definition;b.connectedCallback&&b.connectedCallback.call(a)};v.prototype.disconnectedCallback=function(a){var b=a.__CE_definition;b.disconnectedCallback&&b.disconnectedCallback.call(a)};v.prototype.attributeChangedCallback=function(a,b,c,d,e){var f=a.__CE_definition;f.attributeChangedCallback&&-1<f.observedAttributes.indexOf(b)&&
f.attributeChangedCallback.call(a,b,c,d,e)};ta.prototype.f=function(){this.b&&this.b.disconnect()};ta.prototype.g=function(a){var b=this.a.readyState;"interactive"!==b&&"complete"!==b||this.f();for(b=0;b<a.length;b++)for(var c=a[b].addedNodes,d=0;d<c.length;d++)this.c.f(c[d])};cb.prototype.resolve=function(a){if(this.a)throw Error("Already resolved.");this.a=a;this.b&&this.b(a)};x.prototype.define=function(a,b){var c=this;if(!(b instanceof Function))throw new TypeError("Custom element constructors must be functions.");
if(!lb(a))throw new SyntaxError("The element name '"+a+"' is not valid.");if(this.a.c(a))throw Error("A custom element with name '"+a+"' has already been defined.");if(this.c)throw Error("A custom element is already being defined.");this.c=!0;try{var d=function(a){var b=e[a];if(void 0!==b&&!(b instanceof Function))throw Error("The '"+a+"' callback must be a function.");return b},e=b.prototype;if(!(e instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");
var f=d("connectedCallback");var h=d("disconnectedCallback");var g=d("adoptedCallback");var k=d("attributeChangedCallback");var l=b.observedAttributes||[]}catch(Oc){return}finally{this.c=!1}b={localName:a,constructor:b,connectedCallback:f,disconnectedCallback:h,adoptedCallback:g,attributeChangedCallback:k,observedAttributes:l,constructionStack:[]};this.a.I(a,b);this.g.push(b);this.b||(this.b=!0,this.f(function(){return c.j()}))};x.prototype.j=function(){var a=this;if(!1!==this.b){this.b=!1;for(var b=
this.g,c=[],d=new Map,e=0;e<b.length;e++)d.set(b[e].localName,[]);this.a.f(document,{ra:function(b){if(void 0===b.__CE_state){var e=b.localName,f=d.get(e);f?f.push(b):a.a.c(e)&&c.push(b)}}});for(e=0;e<c.length;e++)this.a.i(c[e]);for(;0<b.length;){var f=b.shift();e=f.localName;f=d.get(f.localName);for(var h=0;h<f.length;h++)this.a.i(f[h]);(e=this.h.get(e))&&e.resolve(void 0)}}};x.prototype.get=function(a){if(a=this.a.c(a))return a.constructor};x.prototype.whenDefined=function(a){if(!lb(a))return Promise.reject(new SyntaxError("'"+
a+"' is not a valid custom element name."));var b=this.h.get(a);if(b)return b.c;b=new cb;this.h.set(a,b);this.a.c(a)&&!this.g.some(function(b){return b.localName===a})&&b.resolve(void 0);return b.c};x.prototype.l=function(a){this.i.f();var b=this.f;this.f=function(c){return a(function(){return b(c)})}};window.CustomElementRegistry=x;x.prototype.define=x.prototype.define;x.prototype.get=x.prototype.get;x.prototype.whenDefined=x.prototype.whenDefined;x.prototype.polyfillWrapFlushCallback=x.prototype.l;
var pa=window.Document.prototype.createElement,bc=window.Document.prototype.createElementNS,ac=window.Document.prototype.importNode,cc=window.Document.prototype.prepend,dc=window.Document.prototype.append,Sa=window.Node.prototype.cloneNode,X=window.Node.prototype.appendChild,$a=window.Node.prototype.insertBefore,qa=window.Node.prototype.removeChild,ab=window.Node.prototype.replaceChild,sa=Object.getOwnPropertyDescriptor(window.Node.prototype,"textContent"),Ra=window.Element.prototype.attachShadow,
na=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),ra=window.Element.prototype.getAttribute,Ta=window.Element.prototype.setAttribute,Va=window.Element.prototype.removeAttribute,Y=window.Element.prototype.getAttributeNS,Ua=window.Element.prototype.setAttributeNS,Wa=window.Element.prototype.removeAttributeNS,Ya=window.Element.prototype.insertAdjacentElement,Sb=window.Element.prototype.prepend,Tb=window.Element.prototype.append,Vb=window.Element.prototype.before,Wb=window.Element.prototype.after,
Xb=window.Element.prototype.replaceWith,Yb=window.Element.prototype.remove,fc=window.HTMLElement,oa=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),Xa=window.HTMLElement.prototype.insertAdjacentElement,bb=new function(){},ea=window.customElements;if(!ea||ea.forcePolyfill||"function"!=typeof ea.define||"function"!=typeof ea.get){var U=new v;ec(U);$b(U);Zb(U);Qb(U);document.__CE_hasRegistry=!0;var Ac=new x(U);Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,
value:Ac})}var F={STYLE_RULE:1,Z:7,MEDIA_RULE:4,fa:1E3},B={Fa:/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,port:/@import[^;]*;/gim,ja:/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,ma:/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,Ka:/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,Na:/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,Ja:/^@[^\s]*keyframes/,na:/\s+/g},u=!(window.ShadyDOM&&window.ShadyDOM.inUse);if(window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss)var n=window.ShadyCSS.nativeCss;else window.ShadyCSS?
(ob(window.ShadyCSS),window.ShadyCSS=void 0):ob(window.WebComponents&&window.WebComponents.flags);var fa=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,ha=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,Bc=/(--[\w-]+)\s*([:,;)]|$)/gi,Cc=/(animation\s*:)|(animation-name\s*:)/,tc=/@media\s(.*)/,Dc=/\{[^}]*\}/g,J=null;p.prototype.a=function(a,b,c){a.__styleScoped?a.__styleScoped=null:this.i(a,b||"",c)};p.prototype.i=function(a,b,c){a.nodeType===
Node.ELEMENT_NODE&&this.H(a,b,c);if(a="template"===a.localName?(a.content||a.Ra).childNodes:a.children||a.childNodes)for(var d=0;d<a.length;d++)this.i(a[d],b,c)};p.prototype.H=function(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute(Ec);c?d&&(b=d.replace("style-scope","").replace(b,""),ba(a,b)):ba(a,(d?d+" ":"")+"style-scope "+b)}};p.prototype.b=function(a,b,c){var d=
a.__cssBuild;u||"shady"===d?b=P(b,c):(a=K(a),b=this.M(b,a.is,a.R,c)+"\n\n");return b.trim()};p.prototype.M=function(a,b,c,d){var e=this.f(b,c);b=this.h(b);var f=this;return P(a,function(a){a.c||(f.O(a,b,e),a.c=!0);d&&d(a,b,e)})};p.prototype.h=function(a){return a?Fc+a:""};p.prototype.f=function(a,b){return b?"[is="+a+"]":a};p.prototype.O=function(a,b,c){this.j(a,this.g,b,c)};p.prototype.j=function(a,b,c,d){a.selector=a.A=this.l(a,b,c,d)};p.prototype.l=function(a,b,c,d){var e=a.selector.split(Bb);
if(!pb(a)){a=0;for(var f=e.length,h;a<f&&(h=e[a]);a++)e[a]=b.call(this,h,c,d)}return e.join(Bb)};p.prototype.u=function(a){return a.replace(Ia,function(a,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})};p.prototype.g=function(a,b,c){var d=this,e=!1;a=a.trim();var f=Ia.test(a);f&&(a=a.replace(Ia,function(a,b,c){return":"+b+"("+c.replace(/\s/g,"")+")"}),a=this.u(a));a=a.replace(Gc,Ja+" $1");a=a.replace(Hc,function(a,f,g){e||(a=d.I(g,
f,b,c),e=e||a.stop,f=a.Ea,g=a.value);return f+g});f&&(a=this.u(a));return a};p.prototype.I=function(a,b,c,d){var e=a.indexOf(Ka);0<=a.indexOf(Ja)?a=this.L(a,d):0!==e&&(a=c?this.s(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(Ic,function(a,b){return" > "+b}))}a=a.replace(Jc,function(a,b,c){return'[dir="'+c+'"] '+b+", "+b+'[dir="'+c+'"]'});return{value:a,Ea:b,stop:f}};p.prototype.s=function(a,b){a=a.split(Cb);a[0]+=b;return a.join(Cb)};p.prototype.L=function(a,b){var c=a.match(Db);return(c=
c&&c[2].trim()||"")?c[0].match(Eb)?a.replace(Db,function(a,c,f){return b+f}):c.split(Eb)[0]===b?c:Kc:a.replace(Ja,b)};p.prototype.N=function(a){a.selector=a.parsedSelector;this.w(a);this.j(a,this.S)};p.prototype.w=function(a){a.selector===Lc&&(a.selector="html")};p.prototype.S=function(a){return a.match(Ka)?this.g(a,Fb):this.s(a.trim(),Fb)};Oa.Object.defineProperties(p.prototype,{c:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});var Ia=/:(nth[-\w]+)\(([^)]+)\)/,Fb=":not(.style-scope)",
Bb=",",Hc=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,Eb=/[[.:#*]/,Ja=":host",Lc=":root",Ka="::slotted",Gc=new RegExp("^("+Ka+")"),Db=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Ic=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Jc=/(.*):dir\((?:(ltr|rtl))\)/,Fc=".",Cb=":",Ec="class",Kc="should_not_match",r=new p;q.get=function(a){return a?a.__styleInfo:null};q.set=function(a,b){return a.__styleInfo=b};q.prototype.c=function(){return this.D};q.prototype._getStyleRules=q.prototype.c;var Gb=function(a){return a.matches||
a.matchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector||a.webkitMatchesSelector}(window.Element.prototype),Mc=navigator.userAgent.match("Trident");l.prototype.N=function(a){var b=this,c={},d=[],e=0;Q(a,function(a){b.c(a);a.index=e++;b.M(a.v.cssText,c)},function(a){d.push(a)});a.b=d;a=[];for(var f in c)a.push(f);return a};l.prototype.c=function(a){if(!a.v){var b={},c={};this.b(a,c)&&(b.C=c,a.rules=null);b.cssText=this.L(a);a.v=b}};l.prototype.b=function(a,b){var c=a.v;if(c){if(c.C)return Object.assign(b,
c.C),!0}else{c=a.parsedCssText;for(var d;a=fa.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}};l.prototype.L=function(a){return this.S(a.parsedCssText)};l.prototype.S=function(a){return a.replace(Dc,"").replace(fa,"")};l.prototype.M=function(a,b){for(var c;c=Bc.exec(a);){var d=c[1];":"!==c[2]&&(b[d]=!0)}};l.prototype.W=function(a){for(var b=Object.getOwnPropertyNames(a),c=0,d;c<b.length;c++)d=b[c],a[d]=this.a(a[d],a)};l.prototype.a=function(a,b){if(a)if(0<=
a.indexOf(";"))a=this.f(a,b);else{var c=this;a=rb(a,function(a,e,f,h){if(!e)return a+h;(e=c.a(b[e],b))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=c.a(b[f]||f,b)||f;return a+(e||"")+h})}return a&&a.trim()||""};l.prototype.f=function(a,b){a=a.split(";");for(var c=0,d,e;c<a.length;c++)if(d=a[c]){ha.lastIndex=0;if(e=ha.exec(d))d=this.a(b[e[1]],b);else if(e=d.indexOf(":"),-1!==e){var f=d.substring(e);f=f.trim();f=this.a(f,b)||f;d=d.substring(0,e)+f}a[c]=d&&d.lastIndexOf(";")===d.length-1?
d.slice(0,-1):d||""}return a.join(";")};l.prototype.I=function(a,b){var c="";a.v||this.c(a);a.v.cssText&&(c=this.f(a.v.cssText,b));a.cssText=c};l.prototype.H=function(a,b){var c=a.cssText,d=a.cssText;null==a.la&&(a.la=Cc.test(c));if(a.la)if(null==a.U){a.U=[];for(var e in b)d=b[e],d=d(c),c!==d&&(c=d,a.U.push(e))}else{for(e=0;e<a.U.length;++e)d=b[a.U[e]],c=d(c);d=c}a.cssText=d};l.prototype.V=function(a,b){var c={},d=this,e=[];Q(a,function(a){a.v||d.c(a);var f=a.A||a.parsedSelector;b&&a.v.C&&f&&Gb.call(b,
f)&&(d.b(a,c),a=a.index,f=parseInt(a/32,10),e[f]=(e[f]||0)|1<<a%32)},null,!0);return{C:c,key:e}};l.prototype.Y=function(a,b,c,d){b.v||this.c(b);if(b.v.C){var e=K(a);a=e.is;e=e.R;e=a?r.f(a,e):"html";var f=b.parsedSelector,h=":host > *"===f||"html"===f,g=0===f.indexOf(":host")&&!h;"shady"===c&&(h=f===e+" > *."+e||-1!==f.indexOf("html"),g=!h&&0===f.indexOf(e));"shadow"===c&&(h=":host > *"===f||"html"===f,g=g&&!h);if(h||g)c=e,g&&(u&&!b.A&&(b.A=r.l(b,r.g,r.h(a),e)),c=b.A||e),d({Ma:c,Ia:g,Va:h})}};l.prototype.O=
function(a,b){var c={},d={},e=this,f=b&&b.__cssBuild;Q(b,function(b){e.Y(a,b,f,function(f){Gb.call(a.Sa||a,f.Ma)&&(f.Ia?e.b(b,c):e.b(b,d))})},null,!0);return{La:d,Ha:c}};l.prototype.X=function(a,b,c){var d=this,e=K(a),f=r.f(e.is,e.R),h=new RegExp("(?:^|[^.#[:])"+(a.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])");e=q.get(a).D;var g=this.h(e,c);return r.b(a,e,function(a){d.I(a,b);u||pb(a)||!a.cssText||(d.H(a,g),d.l(a,h,f,c))})};l.prototype.h=function(a,b){a=a.b;var c={};if(!u&&a)for(var d=0,
e=a[d];d<a.length;e=a[++d])this.j(e,b),c[e.keyframesName]=this.i(e);return c};l.prototype.i=function(a){return function(b){return b.replace(a.f,a.a)}};l.prototype.j=function(a,b){a.f=new RegExp(a.keyframesName,"g");a.a=a.keyframesName+"-"+b;a.A=a.A||a.selector;a.selector=a.A.replace(a.keyframesName,a.a)};l.prototype.l=function(a,b,c,d){a.A=a.A||a.selector;d="."+d;for(var e=a.A.split(","),f=0,h=e.length,g;f<h&&(g=e[f]);f++)e[f]=g.match(b)?g.replace(c,d):d+" "+g;a.selector=e.join(",")};l.prototype.u=
function(a,b,c){var d=a.getAttribute("class")||"",e=d;c&&(e=d.replace(new RegExp("\\s*x-scope\\s*"+c+"\\s*","g")," "));e+=(e?" ":"")+"x-scope "+b;d!==e&&ba(a,e)};l.prototype.w=function(a,b,c,d){b=d?d.textContent||"":this.X(a,b,c);var e=q.get(a),f=e.a;f&&!u&&f!==d&&(f._useCount--,0>=f._useCount&&f.parentNode&&f.parentNode.removeChild(f));u?e.a?(e.a.textContent=b,d=e.a):b&&(d=Ea(b,c,a.shadowRoot,e.b)):d?d.parentNode||(Mc&&-1<b.indexOf("@media")&&(d.textContent=b),qb(d,null,e.b)):b&&(d=Ea(b,c,null,e.b));
d&&(d._useCount=d._useCount||0,e.a!=d&&d._useCount++,e.a=d);return d};l.prototype.s=function(a,b){var c=aa(a),d=this;a.textContent=P(c,function(a){var c=a.cssText=a.parsedCssText;a.v&&a.v.cssText&&(c=c.replace(B.ja,"").replace(B.ma,""),a.cssText=d.f(c,b))})};Oa.Object.defineProperties(l.prototype,{g:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var G=new l,La={},ia=window.customElements;if(ia&&!u){var Nc=ia.define;ia.define=function(a,b,c){var d=document.createComment(" Shady DOM styles for "+
a+" "),e=document.head;e.insertBefore(d,(J?J.nextSibling:null)||e.firstChild);J=d;La[a]=d;return Nc.call(ia,a,b,c)}}W.prototype.b=function(a,b,c){for(var d=0;d<c.length;d++){var e=c[d];if(a.C[e]!==b[e])return!1}return!0};W.prototype.c=function(a,b,c,d){var e=this.cache[a]||[];e.push({C:b,styleElement:c,B:d});e.length>this.f&&e.shift();this.cache[a]=e};W.prototype.a=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d];if(this.b(e,b,c))return e}};if(!u){var Hb=new MutationObserver(sb),
Ib=function(a){Hb.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)Ib(document);else{var Ma=function(){Ib(document.body)};window.HTMLImports?window.HTMLImports.whenReady(Ma):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){Ma();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",a)}else Ma()})}Qa=function(){sb(Hb.takeRecords())}}var ca={},wc=Promise.resolve(),
Fa=null,ub=window.HTMLImports&&window.HTMLImports.whenReady||null,Ga,ja=null,V=null;A.prototype.ka=function(){!this.enqueued&&V&&(this.enqueued=!0,Pa(V))};A.prototype.b=function(a){a.__seenByShadyCSS||(a.__seenByShadyCSS=!0,this.customStyles.push(a),this.ka())};A.prototype.a=function(a){return a.__shadyCSSCachedStyle?a.__shadyCSSCachedStyle:a.getStyle?a.getStyle():a};A.prototype.c=function(){for(var a=this.customStyles,b=0;b<a.length;b++){var c=a[b];if(!c.__shadyCSSCachedStyle){var d=this.a(c);d&&
(d=d.__appliedElement||d,ja&&ja(d),c.__shadyCSSCachedStyle=d)}}return a};A.prototype.addCustomStyle=A.prototype.b;A.prototype.getStyleForCustomStyle=A.prototype.a;A.prototype.processStyles=A.prototype.c;Object.defineProperties(A.prototype,{transformCallback:{get:function(){return ja},set:function(a){ja=a}},validateCallback:{get:function(){return V},set:function(a){var b=!1;V||(b=!0);V=a;b&&this.ka()}}});var Jb=new W;g.prototype.H=function(){Qa()};g.prototype.O=function(a){var b=this.s[a]=(this.s[a]||
0)+1;return a+"-"+b};g.prototype.va=function(a){return aa(a)};g.prototype.xa=function(a){return P(a)};g.prototype.N=function(a){a=a.content.querySelectorAll("style");for(var b=[],c=0;c<a.length;c++){var d=a[c];b.push(d.textContent);d.parentNode.removeChild(d)}return b.join("").trim()};g.prototype.W=function(a){return(a=a.content.querySelector("style"))?a.getAttribute("css-build")||"":""};g.prototype.prepareTemplate=function(a,b,c){if(!a.f){a.f=!0;a.name=b;a.extends=c;ca[b]=a;var d=this.W(a),e=this.N(a);
c={is:b,extends:c,Pa:d};u||r.a(a.content,b);this.c();var f=ha.test(e)||fa.test(e);ha.lastIndex=0;fa.lastIndex=0;e=Da(e);f&&n&&this.a&&this.a.transformRules(e,b);a._styleAst=e;a.g=d;d=[];n||(d=G.N(a._styleAst));if(!d.length||n)b=this.V(c,a._styleAst,u?a.content:null,La[b]),a.a=b;a.c=d}};g.prototype.V=function(a,b,c,d){b=r.b(a,b);if(b.length)return Ea(b,a.is,c,d)};g.prototype.Y=function(a){var b=K(a),c=b.is;b=b.R;var d=La[c];c=ca[c];if(c){var e=c._styleAst;var f=c.c}return q.set(a,new q(e,d,f,0,b))};
g.prototype.L=function(){!this.a&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(this.a=window.ShadyCSS.ApplyShim,this.a.invalidCallback=uc)};g.prototype.M=function(){var a=this;!this.b&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(this.b=window.ShadyCSS.CustomStyleInterface,this.b.transformCallback=function(b){a.w(b)},this.b.validateCallback=function(){requestAnimationFrame(function(){(a.b.enqueued||a.i)&&a.f()})})};g.prototype.c=function(){this.L();this.M()};g.prototype.f=function(){this.c();
if(this.b){var a=this.b.processStyles();this.b.enqueued&&(n?this.ta(a):(this.u(this.g,this.h),this.I(a)),this.b.enqueued=!1,this.i&&!n&&this.styleDocument())}};g.prototype.styleElement=function(a,b){var c=K(a).is,d=q.get(a);d||(d=this.Y(a));this.j(a)||(this.i=!0);b&&(d.K=d.K||{},Object.assign(d.K,b));if(n){if(d.K){b=d.K;for(var e in b)null===e?a.style.removeProperty(e):a.style.setProperty(e,b[e])}if(((e=ca[c])||this.j(a))&&e&&e.a&&!tb(e)){if(tb(e)||e._applyShimValidatingVersion!==e._applyShimNextVersion)this.c(),
this.a&&this.a.transformRules(e._styleAst,c),e.a.textContent=r.b(a,d.D),vc(e);u&&(c=a.shadowRoot)&&(c.querySelector("style").textContent=r.b(a,d.D));d.D=e._styleAst}}else this.u(a,d),d.da&&d.da.length&&this.S(a,d)};g.prototype.l=function(a){return(a=a.getRootNode().host)?q.get(a)?a:this.l(a):this.g};g.prototype.j=function(a){return a===this.g};g.prototype.S=function(a,b){var c=K(a).is,d=Jb.a(c,b.G,b.da),e=d?d.styleElement:null,f=b.B;b.B=d&&d.B||this.O(c);e=G.w(a,b.G,b.B,e);u||G.u(a,b.B,f);d||Jb.c(c,
b.G,e,b.B)};g.prototype.u=function(a,b){var c=this.l(a),d=q.get(c);c=Object.create(d.G||null);var e=G.O(a,b.D);a=G.V(d.D,a).C;Object.assign(c,e.Ha,a,e.La);this.X(c,b.K);G.W(c);b.G=c};g.prototype.X=function(a,b){for(var c in b){var d=b[c];if(d||0===d)a[c]=d}};g.prototype.styleDocument=function(a){this.styleSubtree(this.g,a)};g.prototype.styleSubtree=function(a,b){var c=a.shadowRoot;(c||this.j(a))&&this.styleElement(a,b);if(b=c&&(c.children||c.childNodes))for(a=0;a<b.length;a++)this.styleSubtree(b[a]);
else if(a=a.children||a.childNodes)for(b=0;b<a.length;b++)this.styleSubtree(a[b])};g.prototype.ta=function(a){for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);c&&this.sa(c)}};g.prototype.I=function(a){for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);c&&G.s(c,this.h.G)}};g.prototype.w=function(a){var b=this,c=aa(a);Q(c,function(a){u?r.w(a):r.N(a);n&&(b.c(),b.a&&b.a.transformRule(a))});n?a.textContent=P(c):this.h.D.rules.push(c)};g.prototype.sa=function(a){if(n&&
this.a){var b=aa(a);this.c();this.a.transformRules(b);a.textContent=P(b)}};g.prototype.getComputedStyleValue=function(a,b){var c;n||(c=(q.get(a)||q.get(this.l(a))).G[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};g.prototype.wa=function(a,b){var c=a.getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===r.c){c=d[e+1];break}}}c&&b.push(r.c,c);n||(c=q.get(a))&&c.B&&b.push(G.g,
c.B);ba(a,b.join(" "))};g.prototype.ua=function(a){return q.get(a)};g.prototype.flush=g.prototype.H;g.prototype.prepareTemplate=g.prototype.prepareTemplate;g.prototype.styleElement=g.prototype.styleElement;g.prototype.styleDocument=g.prototype.styleDocument;g.prototype.styleSubtree=g.prototype.styleSubtree;g.prototype.getComputedStyleValue=g.prototype.getComputedStyleValue;g.prototype.setElementClass=g.prototype.wa;g.prototype._styleInfoForNode=g.prototype.ua;g.prototype.transformCustomStyleForDocument=
g.prototype.w;g.prototype.getStyleAst=g.prototype.va;g.prototype.styleAstToString=g.prototype.xa;g.prototype.flushCustomStyles=g.prototype.f;Object.defineProperties(g.prototype,{nativeShadow:{get:function(){return u}},nativeCss:{get:function(){return n}}});var C=new g;if(window.ShadyCSS){var Kb=window.ShadyCSS.ApplyShim;var Lb=window.ShadyCSS.CustomStyleInterface}window.ShadyCSS={ScopingShim:C,prepareTemplate:function(a,b,c){C.f();C.prepareTemplate(a,b,c)},styleSubtree:function(a,b){C.f();C.styleSubtree(a,
b)},styleElement:function(a){C.f();C.styleElement(a)},styleDocument:function(a){C.f();C.styleDocument(a)},getComputedStyleValue:function(a,b){return C.getComputedStyleValue(a,b)},nativeCss:n,nativeShadow:u};Kb&&(window.ShadyCSS.ApplyShim=Kb);Lb&&(window.ShadyCSS.CustomStyleInterface=Lb);var Na=window.customElements,ka=window.HTMLImports;window.WebComponents=window.WebComponents||{};if(Na&&Na.polyfillWrapFlushCallback){var la,Mb=function(){if(la){var a=la;la=null;a();return!0}},Nb=ka.whenReady;Na.polyfillWrapFlushCallback(function(a){la=
a;Nb(Mb)});ka.whenReady=function(a){Nb(function(){Mb()?ka.whenReady(a):a()})}}ka.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})});var Ob=document.createElement("style");Ob.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";var Pb=document.querySelector("head");Pb.insertBefore(Ob,Pb.firstChild)})();}).call(this);

//# sourceMappingURL=webcomponents-lite.js.map
